// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelOAuthSessionOperation       OperationName = "CancelOAuthSession"
	CreateMyAPIKeyOperation           OperationName = "CreateMyAPIKey"
	CreateProviderAPIKeysOperation    OperationName = "CreateProviderAPIKeys"
	DeleteModelOverrideOperation      OperationName = "DeleteModelOverride"
	ExportOAuthCredentialOperation    OperationName = "ExportOAuthCredential"
	GetMyUsageOperation               OperationName = "GetMyUsage"
	GetOAuthSessionOperation          OperationName = "GetOAuthSession"
	GetUpstreamAccountQuotaOperation  OperationName = "GetUpstreamAccountQuota"
	HealthzOperation                  OperationName = "Healthz"
	ImportOAuthCredentialOperation    OperationName = "ImportOAuthCredential"
	ListAllAPIKeysOperation           OperationName = "ListAllAPIKeys"
	ListModelOverridesOperation       OperationName = "ListModelOverrides"
	ListMyAPIKeysOperation            OperationName = "ListMyAPIKeys"
	ListPendingOAuthSessionsOperation OperationName = "ListPendingOAuthSessions"
	ListUsersOperation                OperationName = "ListUsers"
	LoginOperation                    OperationName = "Login"
	MetricsOperation                  OperationName = "Metrics"
	OpenapiJsonOperation              OperationName = "OpenapiJson"
	ReadyzOperation                   OperationName = "Readyz"
	RevokeMyAPIKeyOperation           OperationName = "RevokeMyAPIKey"
	SetUserStatusOperation            OperationName = "SetUserStatus"
	TestUpstreamAccountOperation      OperationName = "TestUpstreamAccount"
	UpsertModelOverrideOperation      OperationName = "UpsertModelOverride"
)
