// Code generated by ogen, DO NOT EDIT.
package ogen

type CancelOAuthSessionRes interface {
	cancelOAuthSessionRes()
}

type CreateMyAPIKeyRes interface {
	createMyAPIKeyRes()
}

type CreateProviderAPIKeysRes interface {
	createProviderAPIKeysRes()
}

type ExportOAuthCredentialRes interface {
	exportOAuthCredentialRes()
}

type GetCurrentUserRes interface {
	getCurrentUserRes()
}

type GetMyUsageRes interface {
	getMyUsageRes()
}

type GetOAuthSessionRes interface {
	getOAuthSessionRes()
}

type GetUpstreamAccountQuotaRes interface {
	getUpstreamAccountQuotaRes()
}

type ImportOAuthCredentialRes interface {
	importOAuthCredentialRes()
}

type ListAllAPIKeysRes interface {
	listAllAPIKeysRes()
}

type ListMyAPIKeysRes interface {
	listMyAPIKeysRes()
}

type ListPendingOAuthSessionsRes interface {
	listPendingOAuthSessionsRes()
}

type ListUsersRes interface {
	listUsersRes()
}

type LoginRes interface {
	loginRes()
}

type ProxyAlphaSearchRes interface {
	proxyAlphaSearchRes()
}

type ProxyChatCompletionsRes interface {
	proxyChatCompletionsRes()
}

type ProxyCodexAlphaSearchRes interface {
	proxyCodexAlphaSearchRes()
}

type ProxyCodexResponsesCompactRes interface {
	proxyCodexResponsesCompactRes()
}

type ProxyCodexResponsesRes interface {
	proxyCodexResponsesRes()
}

type ProxyCodexResponsesWebsocketRes interface {
	proxyCodexResponsesWebsocketRes()
}

type ProxyCompletionsRes interface {
	proxyCompletionsRes()
}

type ProxyGeminiInteractionsRes interface {
	proxyGeminiInteractionsRes()
}

type ProxyGeminiModelActionGetRes interface {
	proxyGeminiModelActionGetRes()
}

type ProxyGeminiModelActionPostRes interface {
	proxyGeminiModelActionPostRes()
}

type ProxyGeminiModelsRes interface {
	proxyGeminiModelsRes()
}

type ProxyImageEditsRes interface {
	proxyImageEditsRes()
}

type ProxyImageGenerationsRes interface {
	proxyImageGenerationsRes()
}

type ProxyMessagesCountTokensRes interface {
	proxyMessagesCountTokensRes()
}

type ProxyMessagesRes interface {
	proxyMessagesRes()
}

type ProxyModelsRes interface {
	proxyModelsRes()
}

type ProxyOpenAIVideosContentRes interface {
	proxyOpenAIVideosContentRes()
}

type ProxyOpenAIVideosCreateRes interface {
	proxyOpenAIVideosCreateRes()
}

type ProxyOpenAIVideosRetrieveRes interface {
	proxyOpenAIVideosRetrieveRes()
}

type ProxyResponsesCompactRes interface {
	proxyResponsesCompactRes()
}

type ProxyResponsesRes interface {
	proxyResponsesRes()
}

type ProxyResponsesWebsocketRes interface {
	proxyResponsesWebsocketRes()
}

type ProxyXAIVideoEditsRes interface {
	proxyXAIVideoEditsRes()
}

type ProxyXAIVideoExtensionsRes interface {
	proxyXAIVideoExtensionsRes()
}

type ProxyXAIVideoGenerationsRes interface {
	proxyXAIVideoGenerationsRes()
}

type ProxyXAIVideoRetrieveRes interface {
	proxyXAIVideoRetrieveRes()
}

type ProxyXAIVideosRes interface {
	proxyXAIVideosRes()
}

type ReadyzRes interface {
	readyzRes()
}

type RevokeMyAPIKeyRes interface {
	revokeMyAPIKeyRes()
}

type SetUserStatusRes interface {
	setUserStatusRes()
}

type TestUpstreamAccountRes interface {
	testUpstreamAccountRes()
}
