// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOAuthSession implements cancelOAuthSession operation.
	//
	// Отменяет pending OAuth-flow и записывает действие в admin audit log.
	//
	// DELETE /api/v1/admin/oauth/sessions/{state}
	CancelOAuthSession(ctx context.Context, params CancelOAuthSessionParams) (CancelOAuthSessionRes, error)
	// CreateMyAPIKey implements createMyAPIKey operation.
	//
	// Создаёт ключ для текущего пользователя. Полное
	// значение возвращается только в ответе `201` и в БД не
	// хранится.
	//
	// POST /api/v1/me/keys
	CreateMyAPIKey(ctx context.Context, req *CreateAPIKeyRequest) (CreateMyAPIKeyRes, error)
	// CreateProviderAPIKeys implements createProviderAPIKeys operation.
	//
	// Регистрирует до 100 статических upstream credentials через public
	// SDK manager. Каждый credential шифруется в Store и записывается в
	// admin audit log; ключи не возвращаются.
	//
	// POST /api/v1/admin/providers/keys
	CreateProviderAPIKeys(ctx context.Context, req *CreateProviderKeysRequest) (CreateProviderAPIKeysRes, error)
	// DeleteModelOverride implements deleteModelOverride operation.
	//
	// Удаление записывается в admin audit log.
	//
	// DELETE /api/v1/admin/models/{modelAlias}
	DeleteModelOverride(ctx context.Context, params DeleteModelOverrideParams) error
	// ExportOAuthCredential implements exportOAuthCredential operation.
	//
	// Отдаёт attachment с полным OAuth credential JSON. Файл содержит
	// access/refresh tokens и должен обрабатываться как секрет;
	// действие записывается в admin audit log.
	//
	// GET /api/v1/admin/oauth/accounts/{accountID}/export
	ExportOAuthCredential(ctx context.Context, params ExportOAuthCredentialParams) (ExportOAuthCredentialRes, error)
	// GetCurrentUser implements getCurrentUser operation.
	//
	// Текущий principal management-сессии.
	//
	// GET /api/v1/me
	GetCurrentUser(ctx context.Context) (GetCurrentUserRes, error)
	// GetMyUsage implements getMyUsage operation.
	//
	// Возвращает агрегаты только текущего пользователя.
	// Если `from` и `to` не переданы, используется последние 30
	// дней.
	//
	// GET /api/v1/me/usage
	GetMyUsage(ctx context.Context, params GetMyUsageParams) (GetMyUsageRes, error)
	// GetOAuthSession implements getOAuthSession operation.
	//
	// Возвращает статус OAuth-flow без PKCE verifier и device code.
	//
	// GET /api/v1/admin/oauth/sessions/{state}
	GetOAuthSession(ctx context.Context, params GetOAuthSessionParams) (GetOAuthSessionRes, error)
	// GetUpstreamAccountQuota implements getUpstreamAccountQuota operation.
	//
	// Возвращает реактивный quota snapshot ядра и, для Antigravity,
	// последний public credits hint. `unknown=true` означает отсутствие
	// наблюдавшихся inference quota-данных, а не доступность квоты.
	//
	// GET /api/v1/admin/accounts/{accountID}/quota
	GetUpstreamAccountQuota(ctx context.Context, params GetUpstreamAccountQuotaParams) (GetUpstreamAccountQuotaRes, error)
	// Healthz implements healthz operation.
	//
	// Возвращает 200, если процесс жив. Не проверяет БД.
	//
	// GET /healthz
	Healthz(ctx context.Context) (HealthzOK, error)
	// ImportOAuthCredential implements importOAuthCredential operation.
	//
	// Импортирует один полный OAuth credential JSON. Дубликат
	// `provider+email` отклоняется; внешний ID игнорируется, новый ID
	// назначает coreauth.Manager. Действие пишется в admin audit log без
	// токенов.
	//
	// POST /api/v1/admin/oauth/import
	ImportOAuthCredential(ctx context.Context, req *OAuthCredential) (ImportOAuthCredentialRes, error)
	// ListAllAPIKeys implements listAllAPIKeys operation.
	//
	// Возвращает безопасные metadata ключей и их владельцев.
	// Полные ключи и bcrypt-хэши не раскрываются.
	//
	// GET /api/v1/admin/keys
	ListAllAPIKeys(ctx context.Context) (ListAllAPIKeysRes, error)
	// ListModelOverrides implements listModelOverrides operation.
	//
	// Возвращает allow-list и provider selection metadata моделей. Поле
	// upstream_model хранит desired mapping до появления публичного SDK hook
	// для rewrite downstream model.
	//
	// GET /api/v1/admin/models
	ListModelOverrides(ctx context.Context) (*ModelOverrideListResponse, error)
	// ListMyAPIKeys implements listMyAPIKeys operation.
	//
	// Возвращает только безопасные метаданные ключей
	// текущего пользователя. Полный ключ и bcrypt-хэш не
	// раскрываются.
	//
	// GET /api/v1/me/keys
	ListMyAPIKeys(ctx context.Context) (ListMyAPIKeysRes, error)
	// ListPendingOAuthSessions implements listPendingOAuthSessions operation.
	//
	// Возвращает pending OAuth-сессии без PKCE verifier и device code.
	//
	// GET /api/v1/admin/oauth/sessions
	ListPendingOAuthSessions(ctx context.Context) (ListPendingOAuthSessionsRes, error)
	// ListUsers implements listUsers operation.
	//
	// Доступно только администратору через session-cookie.
	//
	// GET /api/v1/admin/users
	ListUsers(ctx context.Context) (ListUsersRes, error)
	// Login implements login operation.
	//
	// Проверяет credentials через LDAP либо static source согласно `auth.mode`.
	// В ответ устанавливает opaque cookie; session-token не
	// возвращается в JSON.
	//
	// POST /api/v1/login
	Login(ctx context.Context, req *LoginRequest) (LoginRes, error)
	// Logout implements logout operation.
	//
	// Удаляет session-cookie, если она была передана, и всегда
	// возвращает
	// успешный ответ с инструкцией удалить cookie на клиенте.
	//
	// POST /api/v1/logout
	Logout(ctx context.Context) (*LogoutNoContent, error)
	// Metrics implements metrics operation.
	//
	// Метрики в Prometheus exposition format (R6.5).
	//
	// GET /metrics
	Metrics(ctx context.Context) (MetricsOK, error)
	// OpenapiJson implements openapiJson operation.
	//
	// Отдаёт текущую OpenAPI 3.1 спецификацию сервиса (R11.4).
	// Генерируется из openapi.yaml (может быть embed-нута в
	// бинарник).
	//
	// GET /openapi.json
	OpenapiJson(ctx context.Context) error
	// Readyz implements readyz operation.
	//
	// Возвращает 200, если сервис готов принимать трафик (DB
	// ping успешен).
	// Используется k8s readiness-probe (R6.3).
	//
	// GET /readyz
	Readyz(ctx context.Context) (ReadyzRes, error)
	// RevokeMyAPIKey implements revokeMyAPIKey operation.
	//
	// Отзывает ключ, принадлежащий текущему пользователю.
	//
	// DELETE /api/v1/me/keys/{keyID}
	RevokeMyAPIKey(ctx context.Context, params RevokeMyAPIKeyParams) (RevokeMyAPIKeyRes, error)
	// SetUserStatus implements setUserStatus operation.
	//
	// Блокировка инвалидирует сессии пользователя. Каждое
	// изменение записывается в admin audit log.
	//
	// PATCH /api/v1/admin/users/{userID}
	SetUserStatus(ctx context.Context, req *SetUserStatusRequest, params SetUserStatusParams) (SetUserStatusRes, error)
	// TestUpstreamAccount implements testUpstreamAccount operation.
	//
	// Проверяет OAuth через refresh-token либо API-key через metadata endpoint
	// провайдера. Inference и CountTokens не вызываются; невалидная
	// credential возвращает `200` с `valid=false`.
	//
	// POST /api/v1/admin/accounts/{accountID}/test
	TestUpstreamAccount(ctx context.Context, params TestUpstreamAccountParams) (TestUpstreamAccountRes, error)
	// UpsertModelOverride implements upsertModelOverride operation.
	//
	// Изменение записывается в admin audit log.
	//
	// PUT /api/v1/admin/models/{modelAlias}
	UpsertModelOverride(ctx context.Context, req *UpsertModelOverrideRequest, params UpsertModelOverrideParams) (*ModelOverride, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
