// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

var (
	rn8AllowedHeaders = map[string]string{
		"PUT": "Content-Type",
	}
	rn22AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn6AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn74AllowedHeaders = map[string]string{
		"PATCH": "Content-Type",
	}
	rn27AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn4AllowedHeaders = map[string]string{
		"POST": "Content-Type",
	}
	rn35AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn37AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization",
	}
	rn38AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn60AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn58AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn59AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn32AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn34AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn40AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn49AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn51AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn52AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn53AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn55AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn61AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization",
	}
	rn62AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn69AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn63AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn65AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn67AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn68AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn42AllowedHeaders = map[string]string{
		"POST": "Authorization",
	}
	rn48AllowedHeaders = map[string]string{
		"GET": "Authorization",
	}
	rn47AllowedHeaders = map[string]string{
		"GET":  "Authorization",
		"POST": "Authorization",
	}
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [2]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "api/v1/"

				if l := len("api/v1/"); len(elem) >= l && elem[0:l] == "api/v1/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "admin/"

					if l := len("admin/"); len(elem) >= l && elem[0:l] == "admin/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "accounts/"

						if l := len("accounts/"); len(elem) >= l && elem[0:l] == "accounts/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "accountID"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'q': // Prefix: "quota"

								if l := len("quota"); len(elem) >= l && elem[0:l] == "quota" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleGetUpstreamAccountQuotaRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: nil,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							case 't': // Prefix: "test"

								if l := len("test"); len(elem) >= l && elem[0:l] == "test" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleTestUpstreamAccountRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: nil,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						}

					case 'k': // Prefix: "keys"

						if l := len("keys"); len(elem) >= l && elem[0:l] == "keys" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handleListAllAPIKeysRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'm': // Prefix: "models"

						if l := len("models"); len(elem) >= l && elem[0:l] == "models" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleListModelOverridesRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "modelAlias"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleDeleteModelOverrideRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleUpsertModelOverrideRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "DELETE,PUT",
										allowedHeaders: rn8AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					case 'o': // Prefix: "oauth/"

						if l := len("oauth/"); len(elem) >= l && elem[0:l] == "oauth/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "accounts/"

							if l := len("accounts/"); len(elem) >= l && elem[0:l] == "accounts/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "accountID"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[0] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case '/': // Prefix: "/export"

								if l := len("/export"); len(elem) >= l && elem[0:l] == "/export" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleExportOAuthCredentialRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET",
											allowedHeaders: nil,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'i': // Prefix: "import"

							if l := len("import"); len(elem) >= l && elem[0:l] == "import" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleImportOAuthCredentialRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn22AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}

						case 's': // Prefix: "sessions"

							if l := len("sessions"); len(elem) >= l && elem[0:l] == "sessions" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleListPendingOAuthSessionsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "state"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "DELETE":
										s.handleCancelOAuthSessionRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									case "GET":
										s.handleGetOAuthSessionRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "DELETE,GET",
											allowedHeaders: nil,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						}

					case 'p': // Prefix: "providers/keys"

						if l := len("providers/keys"); len(elem) >= l && elem[0:l] == "providers/keys" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleCreateProviderAPIKeysRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn6AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'u': // Prefix: "users"

						if l := len("users"); len(elem) >= l && elem[0:l] == "users" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleListUsersRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "userID"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "PATCH":
									s.handleSetUserStatusRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "PATCH",
										allowedHeaders: rn74AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "application/json",
									})
								}

								return
							}

						}

					}

				case 'l': // Prefix: "log"

					if l := len("log"); len(elem) >= l && elem[0:l] == "log" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'i': // Prefix: "in"

						if l := len("in"); len(elem) >= l && elem[0:l] == "in" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleLoginRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn27AllowedHeaders,
									acceptPost:     "application/json",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'o': // Prefix: "out"

						if l := len("out"); len(elem) >= l && elem[0:l] == "out" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleLogoutRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: nil,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				case 'm': // Prefix: "me"

					if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleGetCurrentUserRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'k': // Prefix: "keys"

							if l := len("keys"); len(elem) >= l && elem[0:l] == "keys" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "GET":
									s.handleListMyAPIKeysRequest([0]string{}, elemIsEscaped, w, r)
								case "POST":
									s.handleCreateMyAPIKeyRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET,POST",
										allowedHeaders: rn4AllowedHeaders,
										acceptPost:     "application/json",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "keyID"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "DELETE":
										s.handleRevokeMyAPIKeyRequest([1]string{
											args[0],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "DELETE",
											allowedHeaders: nil,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'u': // Prefix: "usage"

							if l := len("usage"); len(elem) >= l && elem[0:l] == "usage" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleGetMyUsageRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: nil,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				}

			case 'b': // Prefix: "backend-api/codex/"

				if l := len("backend-api/codex/"); len(elem) >= l && elem[0:l] == "backend-api/codex/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "alpha/search"

					if l := len("alpha/search"); len(elem) >= l && elem[0:l] == "alpha/search" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "POST":
							s.handleProxyCodexAlphaSearchRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn35AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				case 'r': // Prefix: "responses"

					if l := len("responses"); len(elem) >= l && elem[0:l] == "responses" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "GET":
							s.handleProxyCodexResponsesWebsocketRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handleProxyCodexResponsesRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET,POST",
								allowedHeaders: rn37AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/compact"

						if l := len("/compact"); len(elem) >= l && elem[0:l] == "/compact" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleProxyCodexResponsesCompactRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn38AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					}

				}

			case 'd': // Prefix: "docs"

				if l := len("docs"); len(elem) >= l && elem[0:l] == "docs" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleDocsRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'h': // Prefix: "healthz"

				if l := len("healthz"); len(elem) >= l && elem[0:l] == "healthz" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleHealthzRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'm': // Prefix: "metrics"

				if l := len("metrics"); len(elem) >= l && elem[0:l] == "metrics" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleMetricsRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'o': // Prefix: "opena"

				if l := len("opena"); len(elem) >= l && elem[0:l] == "opena" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'i': // Prefix: "i/v1/videos"

					if l := len("i/v1/videos"); len(elem) >= l && elem[0:l] == "i/v1/videos" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch r.Method {
						case "POST":
							s.handleProxyOpenAIVideosCreateRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "POST",
								allowedHeaders: rn60AllowedHeaders,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "video_id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleProxyOpenAIVideosRetrieveRequest([1]string{
									args[0],
								}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn58AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/content"

							if l := len("/content"); len(elem) >= l && elem[0:l] == "/content" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleProxyOpenAIVideosContentRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn59AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				case 'p': // Prefix: "pi.json"

					if l := len("pi.json"); len(elem) >= l && elem[0:l] == "pi.json" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleOpenapiJsonRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, notAllowedParams{
								allowedMethods: "GET",
								allowedHeaders: nil,
								acceptPost:     "",
								acceptPatch:    "",
							})
						}

						return
					}

				}

			case 'r': // Prefix: "readyz"

				if l := len("readyz"); len(elem) >= l && elem[0:l] == "readyz" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleReadyzRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, notAllowedParams{
							allowedMethods: "GET",
							allowedHeaders: nil,
							acceptPost:     "",
							acceptPatch:    "",
						})
					}

					return
				}

			case 'v': // Prefix: "v1"

				if l := len("v1"); len(elem) >= l && elem[0:l] == "v1" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "alpha/search"

						if l := len("alpha/search"); len(elem) >= l && elem[0:l] == "alpha/search" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleProxyAlphaSearchRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn32AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'c': // Prefix: "c"

						if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'h': // Prefix: "hat/completions"

							if l := len("hat/completions"); len(elem) >= l && elem[0:l] == "hat/completions" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleProxyChatCompletionsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn34AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'o': // Prefix: "ompletions"

							if l := len("ompletions"); len(elem) >= l && elem[0:l] == "ompletions" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleProxyCompletionsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn40AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					case 'i': // Prefix: "images/"

						if l := len("images/"); len(elem) >= l && elem[0:l] == "images/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'e': // Prefix: "edits"

							if l := len("edits"); len(elem) >= l && elem[0:l] == "edits" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleProxyImageEditsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn49AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						case 'g': // Prefix: "generations"

							if l := len("generations"); len(elem) >= l && elem[0:l] == "generations" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleProxyImageGenerationsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn51AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					case 'm': // Prefix: "m"

						if l := len("m"); len(elem) >= l && elem[0:l] == "m" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'e': // Prefix: "essages"

							if l := len("essages"); len(elem) >= l && elem[0:l] == "essages" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch r.Method {
								case "POST":
									s.handleProxyMessagesRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn52AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}
							switch elem[0] {
							case '/': // Prefix: "/count_tokens"

								if l := len("/count_tokens"); len(elem) >= l && elem[0:l] == "/count_tokens" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleProxyMessagesCountTokensRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn53AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						case 'o': // Prefix: "odels"

							if l := len("odels"); len(elem) >= l && elem[0:l] == "odels" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleProxyModelsRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn55AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					case 'r': // Prefix: "responses"

						if l := len("responses"); len(elem) >= l && elem[0:l] == "responses" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleProxyResponsesWebsocketRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handleProxyResponsesRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET,POST",
									allowedHeaders: rn61AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/compact"

							if l := len("/compact"); len(elem) >= l && elem[0:l] == "/compact" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "POST":
									s.handleProxyResponsesCompactRequest([0]string{}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "POST",
										allowedHeaders: rn62AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					case 'v': // Prefix: "videos"

						if l := len("videos"); len(elem) >= l && elem[0:l] == "videos" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "POST":
								s.handleProxyXAIVideosRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn69AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'e': // Prefix: "e"
								origElem := elem
								if l := len("e"); len(elem) >= l && elem[0:l] == "e" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'd': // Prefix: "dits"

									if l := len("dits"); len(elem) >= l && elem[0:l] == "dits" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleProxyXAIVideoEditsRequest([0]string{}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn63AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}

								case 'x': // Prefix: "xtensions"

									if l := len("xtensions"); len(elem) >= l && elem[0:l] == "xtensions" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch r.Method {
										case "POST":
											s.handleProxyXAIVideoExtensionsRequest([0]string{}, elemIsEscaped, w, r)
										default:
											s.notAllowed(w, r, notAllowedParams{
												allowedMethods: "POST",
												allowedHeaders: rn65AllowedHeaders,
												acceptPost:     "",
												acceptPatch:    "",
											})
										}

										return
									}

								}

								elem = origElem
							case 'g': // Prefix: "generations"
								origElem := elem
								if l := len("generations"); len(elem) >= l && elem[0:l] == "generations" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "POST":
										s.handleProxyXAIVideoGenerationsRequest([0]string{}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "POST",
											allowedHeaders: rn67AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

								elem = origElem
							}
							// Param: "request_id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "GET":
									s.handleProxyXAIVideoRetrieveRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, notAllowedParams{
										allowedMethods: "GET",
										allowedHeaders: rn68AllowedHeaders,
										acceptPost:     "",
										acceptPatch:    "",
									})
								}

								return
							}

						}

					}

				case 'b': // Prefix: "beta/"

					if l := len("beta/"); len(elem) >= l && elem[0:l] == "beta/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'i': // Prefix: "interactions"

						if l := len("interactions"); len(elem) >= l && elem[0:l] == "interactions" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "POST":
								s.handleProxyGeminiInteractionsRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "POST",
									allowedHeaders: rn42AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}

					case 'm': // Prefix: "models"

						if l := len("models"); len(elem) >= l && elem[0:l] == "models" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleProxyGeminiModelsRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, notAllowedParams{
									allowedMethods: "GET",
									allowedHeaders: rn48AllowedHeaders,
									acceptPost:     "",
									acceptPatch:    "",
								})
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "model"
							// Match until ":"
							idx := strings.IndexByte(elem, ':')
							if idx < 0 {
								idx = len(elem)
							}
							args[0] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case ':': // Prefix: ":"

								if l := len(":"); len(elem) >= l && elem[0:l] == ":" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "action"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch r.Method {
									case "GET":
										s.handleProxyGeminiModelActionGetRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									case "POST":
										s.handleProxyGeminiModelActionPostRequest([2]string{
											args[0],
											args[1],
										}, elemIsEscaped, w, r)
									default:
										s.notAllowed(w, r, notAllowedParams{
											allowedMethods: "GET,POST",
											allowedHeaders: rn47AllowedHeaders,
											acceptPost:     "",
											acceptPatch:    "",
										})
									}

									return
								}

							}

						}

					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name           string
	summary        string
	operationID    string
	operationGroup string
	pathPattern    string
	count          int
	args           [2]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// OperationGroup returns the x-ogen-operation-group value.
func (r Route) OperationGroup() string {
	return r.operationGroup
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "api/v1/"

				if l := len("api/v1/"); len(elem) >= l && elem[0:l] == "api/v1/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "admin/"

					if l := len("admin/"); len(elem) >= l && elem[0:l] == "admin/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "accounts/"

						if l := len("accounts/"); len(elem) >= l && elem[0:l] == "accounts/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "accountID"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'q': // Prefix: "quota"

								if l := len("quota"); len(elem) >= l && elem[0:l] == "quota" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = GetUpstreamAccountQuotaOperation
										r.summary = "Просмотреть runtime-квоту upstream аккаунта"
										r.operationID = "getUpstreamAccountQuota"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/admin/accounts/{accountID}/quota"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							case 't': // Prefix: "test"

								if l := len("test"); len(elem) >= l && elem[0:l] == "test" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = TestUpstreamAccountOperation
										r.summary = "Проверить upstream credential"
										r.operationID = "testUpstreamAccount"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/admin/accounts/{accountID}/test"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						}

					case 'k': // Prefix: "keys"

						if l := len("keys"); len(elem) >= l && elem[0:l] == "keys" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = ListAllAPIKeysOperation
								r.summary = "Список всех пользовательских API-ключей"
								r.operationID = "listAllAPIKeys"
								r.operationGroup = ""
								r.pathPattern = "/api/v1/admin/keys"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'm': // Prefix: "models"

						if l := len("models"); len(elem) >= l && elem[0:l] == "models" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = ListModelOverridesOperation
								r.summary = "Список model overrides"
								r.operationID = "listModelOverrides"
								r.operationGroup = ""
								r.pathPattern = "/api/v1/admin/models"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "modelAlias"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = DeleteModelOverrideOperation
									r.summary = "Удалить model override"
									r.operationID = "deleteModelOverride"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/admin/models/{modelAlias}"
									r.args = args
									r.count = 1
									return r, true
								case "PUT":
									r.name = UpsertModelOverrideOperation
									r.summary = "Создать или обновить model override"
									r.operationID = "upsertModelOverride"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/admin/models/{modelAlias}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					case 'o': // Prefix: "oauth/"

						if l := len("oauth/"); len(elem) >= l && elem[0:l] == "oauth/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'a': // Prefix: "accounts/"

							if l := len("accounts/"); len(elem) >= l && elem[0:l] == "accounts/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "accountID"
							// Match until "/"
							idx := strings.IndexByte(elem, '/')
							if idx < 0 {
								idx = len(elem)
							}
							args[0] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case '/': // Prefix: "/export"

								if l := len("/export"); len(elem) >= l && elem[0:l] == "/export" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = ExportOAuthCredentialOperation
										r.summary = "Экспортировать OAuth credential"
										r.operationID = "exportOAuthCredential"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/admin/oauth/accounts/{accountID}/export"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						case 'i': // Prefix: "import"

							if l := len("import"); len(elem) >= l && elem[0:l] == "import" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ImportOAuthCredentialOperation
									r.summary = "Импортировать OAuth credential"
									r.operationID = "importOAuthCredential"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/admin/oauth/import"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 's': // Prefix: "sessions"

							if l := len("sessions"); len(elem) >= l && elem[0:l] == "sessions" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ListPendingOAuthSessionsOperation
									r.summary = "Pending OAuth-сессии"
									r.operationID = "listPendingOAuthSessions"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/admin/oauth/sessions"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "state"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "DELETE":
										r.name = CancelOAuthSessionOperation
										r.summary = "Отменить OAuth-сессию"
										r.operationID = "cancelOAuthSession"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/admin/oauth/sessions/{state}"
										r.args = args
										r.count = 1
										return r, true
									case "GET":
										r.name = GetOAuthSessionOperation
										r.summary = "Статус OAuth-сессии"
										r.operationID = "getOAuthSession"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/admin/oauth/sessions/{state}"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						}

					case 'p': // Prefix: "providers/keys"

						if l := len("providers/keys"); len(elem) >= l && elem[0:l] == "providers/keys" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = CreateProviderAPIKeysOperation
								r.summary = "Зарегистрировать upstream API-keys"
								r.operationID = "createProviderAPIKeys"
								r.operationGroup = ""
								r.pathPattern = "/api/v1/admin/providers/keys"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'u': // Prefix: "users"

						if l := len("users"); len(elem) >= l && elem[0:l] == "users" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = ListUsersOperation
								r.summary = "Список пользователей"
								r.operationID = "listUsers"
								r.operationGroup = ""
								r.pathPattern = "/api/v1/admin/users"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "userID"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "PATCH":
									r.name = SetUserStatusOperation
									r.summary = "Изменить статус пользователя"
									r.operationID = "setUserStatus"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/admin/users/{userID}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				case 'l': // Prefix: "log"

					if l := len("log"); len(elem) >= l && elem[0:l] == "log" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'i': // Prefix: "in"

						if l := len("in"); len(elem) >= l && elem[0:l] == "in" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = LoginOperation
								r.summary = "Login через активный identity source"
								r.operationID = "login"
								r.operationGroup = ""
								r.pathPattern = "/api/v1/login"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'o': // Prefix: "out"

						if l := len("out"); len(elem) >= l && elem[0:l] == "out" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = LogoutOperation
								r.summary = "Завершение management-сессии"
								r.operationID = "logout"
								r.operationGroup = ""
								r.pathPattern = "/api/v1/logout"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				case 'm': // Prefix: "me"

					if l := len("me"); len(elem) >= l && elem[0:l] == "me" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = GetCurrentUserOperation
							r.summary = "Текущий principal management-сессии"
							r.operationID = "getCurrentUser"
							r.operationGroup = ""
							r.pathPattern = "/api/v1/me"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'k': // Prefix: "keys"

							if l := len("keys"); len(elem) >= l && elem[0:l] == "keys" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "GET":
									r.name = ListMyAPIKeysOperation
									r.summary = "Список собственных API-ключей"
									r.operationID = "listMyAPIKeys"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/me/keys"
									r.args = args
									r.count = 0
									return r, true
								case "POST":
									r.name = CreateMyAPIKeyOperation
									r.summary = "Выпустить API-ключ"
									r.operationID = "createMyAPIKey"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/me/keys"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/"

								if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "keyID"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[0] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "DELETE":
										r.name = RevokeMyAPIKeyOperation
										r.summary = "Отозвать API-ключ"
										r.operationID = "revokeMyAPIKey"
										r.operationGroup = ""
										r.pathPattern = "/api/v1/me/keys/{keyID}"
										r.args = args
										r.count = 1
										return r, true
									default:
										return
									}
								}

							}

						case 'u': // Prefix: "usage"

							if l := len("usage"); len(elem) >= l && elem[0:l] == "usage" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = GetMyUsageOperation
									r.summary = "Личная usage-статистика"
									r.operationID = "getMyUsage"
									r.operationGroup = ""
									r.pathPattern = "/api/v1/me/usage"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					}

				}

			case 'b': // Prefix: "backend-api/codex/"

				if l := len("backend-api/codex/"); len(elem) >= l && elem[0:l] == "backend-api/codex/" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'a': // Prefix: "alpha/search"

					if l := len("alpha/search"); len(elem) >= l && elem[0:l] == "alpha/search" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "POST":
							r.name = ProxyCodexAlphaSearchOperation
							r.summary = "Direct Codex alpha search"
							r.operationID = "proxyCodexAlphaSearch"
							r.operationGroup = ""
							r.pathPattern = "/backend-api/codex/alpha/search"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				case 'r': // Prefix: "responses"

					if l := len("responses"); len(elem) >= l && elem[0:l] == "responses" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "GET":
							r.name = ProxyCodexResponsesWebsocketOperation
							r.summary = "Direct Codex Responses websocket"
							r.operationID = "proxyCodexResponsesWebsocket"
							r.operationGroup = ""
							r.pathPattern = "/backend-api/codex/responses"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = ProxyCodexResponsesOperation
							r.summary = "Direct Codex Responses API request"
							r.operationID = "proxyCodexResponses"
							r.operationGroup = ""
							r.pathPattern = "/backend-api/codex/responses"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/compact"

						if l := len("/compact"); len(elem) >= l && elem[0:l] == "/compact" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = ProxyCodexResponsesCompactOperation
								r.summary = "Direct Codex Responses compaction"
								r.operationID = "proxyCodexResponsesCompact"
								r.operationGroup = ""
								r.pathPattern = "/backend-api/codex/responses/compact"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				}

			case 'd': // Prefix: "docs"

				if l := len("docs"); len(elem) >= l && elem[0:l] == "docs" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = DocsOperation
						r.summary = "Интерактивная документация API"
						r.operationID = "docs"
						r.operationGroup = ""
						r.pathPattern = "/docs"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'h': // Prefix: "healthz"

				if l := len("healthz"); len(elem) >= l && elem[0:l] == "healthz" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = HealthzOperation
						r.summary = "Liveness probe"
						r.operationID = "healthz"
						r.operationGroup = ""
						r.pathPattern = "/healthz"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'm': // Prefix: "metrics"

				if l := len("metrics"); len(elem) >= l && elem[0:l] == "metrics" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = MetricsOperation
						r.summary = "Prometheus metrics"
						r.operationID = "metrics"
						r.operationGroup = ""
						r.pathPattern = "/metrics"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'o': // Prefix: "opena"

				if l := len("opena"); len(elem) >= l && elem[0:l] == "opena" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'i': // Prefix: "i/v1/videos"

					if l := len("i/v1/videos"); len(elem) >= l && elem[0:l] == "i/v1/videos" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						switch method {
						case "POST":
							r.name = ProxyOpenAIVideosCreateOperation
							r.summary = "OpenAI video creation"
							r.operationID = "proxyOpenAIVideosCreate"
							r.operationGroup = ""
							r.pathPattern = "/openai/v1/videos"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}
					switch elem[0] {
					case '/': // Prefix: "/"

						if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
							elem = elem[l:]
						} else {
							break
						}

						// Param: "video_id"
						// Match until "/"
						idx := strings.IndexByte(elem, '/')
						if idx < 0 {
							idx = len(elem)
						}
						args[0] = elem[:idx]
						elem = elem[idx:]

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = ProxyOpenAIVideosRetrieveOperation
								r.summary = "Получить OpenAI video request"
								r.operationID = "proxyOpenAIVideosRetrieve"
								r.operationGroup = ""
								r.pathPattern = "/openai/v1/videos/{video_id}"
								r.args = args
								r.count = 1
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/content"

							if l := len("/content"); len(elem) >= l && elem[0:l] == "/content" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ProxyOpenAIVideosContentOperation
									r.summary = "Получить OpenAI video content"
									r.operationID = "proxyOpenAIVideosContent"
									r.operationGroup = ""
									r.pathPattern = "/openai/v1/videos/{video_id}/content"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				case 'p': // Prefix: "pi.json"

					if l := len("pi.json"); len(elem) >= l && elem[0:l] == "pi.json" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = OpenapiJsonOperation
							r.summary = "OpenAPI спецификация"
							r.operationID = "openapiJson"
							r.operationGroup = ""
							r.pathPattern = "/openapi.json"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			case 'r': // Prefix: "readyz"

				if l := len("readyz"); len(elem) >= l && elem[0:l] == "readyz" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = ReadyzOperation
						r.summary = "Readiness probe"
						r.operationID = "readyz"
						r.operationGroup = ""
						r.pathPattern = "/readyz"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'v': // Prefix: "v1"

				if l := len("v1"); len(elem) >= l && elem[0:l] == "v1" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case '/': // Prefix: "/"

					if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "alpha/search"

						if l := len("alpha/search"); len(elem) >= l && elem[0:l] == "alpha/search" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = ProxyAlphaSearchOperation
								r.summary = "Codex alpha search"
								r.operationID = "proxyAlphaSearch"
								r.operationGroup = ""
								r.pathPattern = "/v1/alpha/search"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'c': // Prefix: "c"

						if l := len("c"); len(elem) >= l && elem[0:l] == "c" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'h': // Prefix: "hat/completions"

							if l := len("hat/completions"); len(elem) >= l && elem[0:l] == "hat/completions" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ProxyChatCompletionsOperation
									r.summary = "OpenAI-compatible chat completion"
									r.operationID = "proxyChatCompletions"
									r.operationGroup = ""
									r.pathPattern = "/v1/chat/completions"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 'o': // Prefix: "ompletions"

							if l := len("ompletions"); len(elem) >= l && elem[0:l] == "ompletions" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ProxyCompletionsOperation
									r.summary = "OpenAI-compatible completion"
									r.operationID = "proxyCompletions"
									r.operationGroup = ""
									r.pathPattern = "/v1/completions"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					case 'i': // Prefix: "images/"

						if l := len("images/"); len(elem) >= l && elem[0:l] == "images/" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'e': // Prefix: "edits"

							if l := len("edits"); len(elem) >= l && elem[0:l] == "edits" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ProxyImageEditsOperation
									r.summary = "OpenAI-compatible image edit"
									r.operationID = "proxyImageEdits"
									r.operationGroup = ""
									r.pathPattern = "/v1/images/edits"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						case 'g': // Prefix: "generations"

							if l := len("generations"); len(elem) >= l && elem[0:l] == "generations" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ProxyImageGenerationsOperation
									r.summary = "OpenAI-compatible image generation"
									r.operationID = "proxyImageGenerations"
									r.operationGroup = ""
									r.pathPattern = "/v1/images/generations"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					case 'm': // Prefix: "m"

						if l := len("m"); len(elem) >= l && elem[0:l] == "m" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							break
						}
						switch elem[0] {
						case 'e': // Prefix: "essages"

							if l := len("essages"); len(elem) >= l && elem[0:l] == "essages" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								switch method {
								case "POST":
									r.name = ProxyMessagesOperation
									r.summary = "Anthropic-compatible message"
									r.operationID = "proxyMessages"
									r.operationGroup = ""
									r.pathPattern = "/v1/messages"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}
							switch elem[0] {
							case '/': // Prefix: "/count_tokens"

								if l := len("/count_tokens"); len(elem) >= l && elem[0:l] == "/count_tokens" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = ProxyMessagesCountTokensOperation
										r.summary = "Anthropic-compatible token count"
										r.operationID = "proxyMessagesCountTokens"
										r.operationGroup = ""
										r.pathPattern = "/v1/messages/count_tokens"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}

							}

						case 'o': // Prefix: "odels"

							if l := len("odels"); len(elem) >= l && elem[0:l] == "odels" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ProxyModelsOperation
									r.summary = "List available models"
									r.operationID = "proxyModels"
									r.operationGroup = ""
									r.pathPattern = "/v1/models"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					case 'r': // Prefix: "responses"

						if l := len("responses"); len(elem) >= l && elem[0:l] == "responses" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = ProxyResponsesWebsocketOperation
								r.summary = "OpenAI Responses websocket"
								r.operationID = "proxyResponsesWebsocket"
								r.operationGroup = ""
								r.pathPattern = "/v1/responses"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = ProxyResponsesOperation
								r.summary = "OpenAI Responses API request"
								r.operationID = "proxyResponses"
								r.operationGroup = ""
								r.pathPattern = "/v1/responses"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/compact"

							if l := len("/compact"); len(elem) >= l && elem[0:l] == "/compact" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "POST":
									r.name = ProxyResponsesCompactOperation
									r.summary = "OpenAI Responses compaction"
									r.operationID = "proxyResponsesCompact"
									r.operationGroup = ""
									r.pathPattern = "/v1/responses/compact"
									r.args = args
									r.count = 0
									return r, true
								default:
									return
								}
							}

						}

					case 'v': // Prefix: "videos"

						if l := len("videos"); len(elem) >= l && elem[0:l] == "videos" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "POST":
								r.name = ProxyXAIVideosOperation
								r.summary = "xAI-compatible video generation"
								r.operationID = "proxyXAIVideos"
								r.operationGroup = ""
								r.pathPattern = "/v1/videos"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case 'e': // Prefix: "e"
								origElem := elem
								if l := len("e"); len(elem) >= l && elem[0:l] == "e" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									break
								}
								switch elem[0] {
								case 'd': // Prefix: "dits"

									if l := len("dits"); len(elem) >= l && elem[0:l] == "dits" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = ProxyXAIVideoEditsOperation
											r.summary = "xAI video edit"
											r.operationID = "proxyXAIVideoEdits"
											r.operationGroup = ""
											r.pathPattern = "/v1/videos/edits"
											r.args = args
											r.count = 0
											return r, true
										default:
											return
										}
									}

								case 'x': // Prefix: "xtensions"

									if l := len("xtensions"); len(elem) >= l && elem[0:l] == "xtensions" {
										elem = elem[l:]
									} else {
										break
									}

									if len(elem) == 0 {
										// Leaf node.
										switch method {
										case "POST":
											r.name = ProxyXAIVideoExtensionsOperation
											r.summary = "xAI video extension"
											r.operationID = "proxyXAIVideoExtensions"
											r.operationGroup = ""
											r.pathPattern = "/v1/videos/extensions"
											r.args = args
											r.count = 0
											return r, true
										default:
											return
										}
									}

								}

								elem = origElem
							case 'g': // Prefix: "generations"
								origElem := elem
								if l := len("generations"); len(elem) >= l && elem[0:l] == "generations" {
									elem = elem[l:]
								} else {
									break
								}

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "POST":
										r.name = ProxyXAIVideoGenerationsOperation
										r.summary = "xAI video generation"
										r.operationID = "proxyXAIVideoGenerations"
										r.operationGroup = ""
										r.pathPattern = "/v1/videos/generations"
										r.args = args
										r.count = 0
										return r, true
									default:
										return
									}
								}

								elem = origElem
							}
							// Param: "request_id"
							// Leaf parameter, slashes are prohibited
							idx := strings.IndexByte(elem, '/')
							if idx >= 0 {
								break
							}
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "GET":
									r.name = ProxyXAIVideoRetrieveOperation
									r.summary = "Получить результат xAI video request"
									r.operationID = "proxyXAIVideoRetrieve"
									r.operationGroup = ""
									r.pathPattern = "/v1/videos/{request_id}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

						}

					}

				case 'b': // Prefix: "beta/"

					if l := len("beta/"); len(elem) >= l && elem[0:l] == "beta/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'i': // Prefix: "interactions"

						if l := len("interactions"); len(elem) >= l && elem[0:l] == "interactions" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "POST":
								r.name = ProxyGeminiInteractionsOperation
								r.summary = "Gemini-compatible interaction"
								r.operationID = "proxyGeminiInteractions"
								r.operationGroup = ""
								r.pathPattern = "/v1beta/interactions"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'm': // Prefix: "models"

						if l := len("models"); len(elem) >= l && elem[0:l] == "models" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = ProxyGeminiModelsOperation
								r.summary = "Gemini-compatible model list"
								r.operationID = "proxyGeminiModels"
								r.operationGroup = ""
								r.pathPattern = "/v1beta/models"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"

							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "model"
							// Match until ":"
							idx := strings.IndexByte(elem, ':')
							if idx < 0 {
								idx = len(elem)
							}
							args[0] = elem[:idx]
							elem = elem[idx:]

							if len(elem) == 0 {
								break
							}
							switch elem[0] {
							case ':': // Prefix: ":"

								if l := len(":"); len(elem) >= l && elem[0:l] == ":" {
									elem = elem[l:]
								} else {
									break
								}

								// Param: "action"
								// Leaf parameter, slashes are prohibited
								idx := strings.IndexByte(elem, '/')
								if idx >= 0 {
									break
								}
								args[1] = elem
								elem = ""

								if len(elem) == 0 {
									// Leaf node.
									switch method {
									case "GET":
										r.name = ProxyGeminiModelActionGetOperation
										r.summary = "Gemini-compatible model action via GET"
										r.operationID = "proxyGeminiModelActionGet"
										r.operationGroup = ""
										r.pathPattern = "/v1beta/models/{model}:{action}"
										r.args = args
										r.count = 2
										return r, true
									case "POST":
										r.name = ProxyGeminiModelActionPostOperation
										r.summary = "Gemini-compatible model action via POST"
										r.operationID = "proxyGeminiModelActionPost"
										r.operationGroup = ""
										r.pathPattern = "/v1beta/models/{model}:{action}"
										r.args = args
										r.count = 2
										return r, true
									default:
										return
									}
								}

							}

						}

					}

				}

			}

		}
	}
	return r, false
}
