// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"net/http"
	"net/url"
	"time"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// CancelOAuthSessionParams is parameters of cancelOAuthSession operation.
type CancelOAuthSessionParams struct {
	State string
}

func unpackCancelOAuthSessionParams(packed middleware.Parameters) (params CancelOAuthSessionParams) {
	{
		key := middleware.ParameterKey{
			Name: "state",
			In:   "path",
		}
		params.State = packed[key].(string)
	}
	return params
}

func decodeCancelOAuthSessionParams(args [1]string, argsEscaped bool, r *http.Request) (params CancelOAuthSessionParams, _ error) {
	// Decode path: state.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "state",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.State = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "state",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteModelOverrideParams is parameters of deleteModelOverride operation.
type DeleteModelOverrideParams struct {
	ModelAlias string
}

func unpackDeleteModelOverrideParams(packed middleware.Parameters) (params DeleteModelOverrideParams) {
	{
		key := middleware.ParameterKey{
			Name: "modelAlias",
			In:   "path",
		}
		params.ModelAlias = packed[key].(string)
	}
	return params
}

func decodeDeleteModelOverrideParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteModelOverrideParams, _ error) {
	// Decode path: modelAlias.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "modelAlias",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ModelAlias = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "modelAlias",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ExportOAuthCredentialParams is parameters of exportOAuthCredential operation.
type ExportOAuthCredentialParams struct {
	AccountID string
}

func unpackExportOAuthCredentialParams(packed middleware.Parameters) (params ExportOAuthCredentialParams) {
	{
		key := middleware.ParameterKey{
			Name: "accountID",
			In:   "path",
		}
		params.AccountID = packed[key].(string)
	}
	return params
}

func decodeExportOAuthCredentialParams(args [1]string, argsEscaped bool, r *http.Request) (params ExportOAuthCredentialParams, _ error) {
	// Decode path: accountID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "accountID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccountID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "accountID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetMyUsageParams is parameters of getMyUsage operation.
type GetMyUsageParams struct {
	From OptDateTime `json:",omitempty,omitzero"`
	To   OptDateTime `json:",omitempty,omitzero"`
}

func unpackGetMyUsageParams(packed middleware.Parameters) (params GetMyUsageParams) {
	{
		key := middleware.ParameterKey{
			Name: "from",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.From = v.(OptDateTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "to",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.To = v.(OptDateTime)
		}
	}
	return params
}

func decodeGetMyUsageParams(args [0]string, argsEscaped bool, r *http.Request) (params GetMyUsageParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: from.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "from",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotFromVal time.Time
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToDateTime(val)
					if err != nil {
						return err
					}

					paramsDotFromVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.From.SetTo(paramsDotFromVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "from",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: to.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "to",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotToVal time.Time
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToDateTime(val)
					if err != nil {
						return err
					}

					paramsDotToVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.To.SetTo(paramsDotToVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "to",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetOAuthSessionParams is parameters of getOAuthSession operation.
type GetOAuthSessionParams struct {
	State string
}

func unpackGetOAuthSessionParams(packed middleware.Parameters) (params GetOAuthSessionParams) {
	{
		key := middleware.ParameterKey{
			Name: "state",
			In:   "path",
		}
		params.State = packed[key].(string)
	}
	return params
}

func decodeGetOAuthSessionParams(args [1]string, argsEscaped bool, r *http.Request) (params GetOAuthSessionParams, _ error) {
	// Decode path: state.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "state",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.State = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "state",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetUpstreamAccountQuotaParams is parameters of getUpstreamAccountQuota operation.
type GetUpstreamAccountQuotaParams struct {
	AccountID string
}

func unpackGetUpstreamAccountQuotaParams(packed middleware.Parameters) (params GetUpstreamAccountQuotaParams) {
	{
		key := middleware.ParameterKey{
			Name: "accountID",
			In:   "path",
		}
		params.AccountID = packed[key].(string)
	}
	return params
}

func decodeGetUpstreamAccountQuotaParams(args [1]string, argsEscaped bool, r *http.Request) (params GetUpstreamAccountQuotaParams, _ error) {
	// Decode path: accountID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "accountID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccountID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "accountID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ProxyGenerateContentParams is parameters of proxyGenerateContent operation.
type ProxyGenerateContentParams struct {
	// Идентификатор модели, интерпретируемый upstream SDK.
	Model string
}

func unpackProxyGenerateContentParams(packed middleware.Parameters) (params ProxyGenerateContentParams) {
	{
		key := middleware.ParameterKey{
			Name: "model",
			In:   "path",
		}
		params.Model = packed[key].(string)
	}
	return params
}

func decodeProxyGenerateContentParams(args [1]string, argsEscaped bool, r *http.Request) (params ProxyGenerateContentParams, _ error) {
	// Decode path: model.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "model",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Model = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "model",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// RevokeMyAPIKeyParams is parameters of revokeMyAPIKey operation.
type RevokeMyAPIKeyParams struct {
	KeyID int64
}

func unpackRevokeMyAPIKeyParams(packed middleware.Parameters) (params RevokeMyAPIKeyParams) {
	{
		key := middleware.ParameterKey{
			Name: "keyID",
			In:   "path",
		}
		params.KeyID = packed[key].(int64)
	}
	return params
}

func decodeRevokeMyAPIKeyParams(args [1]string, argsEscaped bool, r *http.Request) (params RevokeMyAPIKeyParams, _ error) {
	// Decode path: keyID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "keyID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.KeyID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           1,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(params.KeyID)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "keyID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SetUserStatusParams is parameters of setUserStatus operation.
type SetUserStatusParams struct {
	UserID int64
}

func unpackSetUserStatusParams(packed middleware.Parameters) (params SetUserStatusParams) {
	{
		key := middleware.ParameterKey{
			Name: "userID",
			In:   "path",
		}
		params.UserID = packed[key].(int64)
	}
	return params
}

func decodeSetUserStatusParams(args [1]string, argsEscaped bool, r *http.Request) (params SetUserStatusParams, _ error) {
	// Decode path: userID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "userID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.UserID = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           1,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(params.UserID)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "userID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// TestUpstreamAccountParams is parameters of testUpstreamAccount operation.
type TestUpstreamAccountParams struct {
	AccountID string
}

func unpackTestUpstreamAccountParams(packed middleware.Parameters) (params TestUpstreamAccountParams) {
	{
		key := middleware.ParameterKey{
			Name: "accountID",
			In:   "path",
		}
		params.AccountID = packed[key].(string)
	}
	return params
}

func decodeTestUpstreamAccountParams(args [1]string, argsEscaped bool, r *http.Request) (params TestUpstreamAccountParams, _ error) {
	// Decode path: accountID.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "accountID",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccountID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "accountID",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpsertModelOverrideParams is parameters of upsertModelOverride operation.
type UpsertModelOverrideParams struct {
	ModelAlias string
}

func unpackUpsertModelOverrideParams(packed middleware.Parameters) (params UpsertModelOverrideParams) {
	{
		key := middleware.ParameterKey{
			Name: "modelAlias",
			In:   "path",
		}
		params.ModelAlias = packed[key].(string)
	}
	return params
}

func decodeUpsertModelOverrideParams(args [1]string, argsEscaped bool, r *http.Request) (params UpsertModelOverrideParams, _ error) {
	// Decode path: modelAlias.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "modelAlias",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ModelAlias = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "modelAlias",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
