// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
	"net/url"
	"strings"
	"time"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/otelogen"
	"github.com/ogen-go/ogen/uri"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
	semconv "go.opentelemetry.io/otel/semconv/v1.39.0"
	"go.opentelemetry.io/otel/trace"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// CancelOAuthSession invokes cancelOAuthSession operation.
	//
	// Отменяет pending OAuth-flow и записывает действие в admin audit log.
	//
	// DELETE /api/v1/admin/oauth/sessions/{state}
	CancelOAuthSession(ctx context.Context, params CancelOAuthSessionParams) (CancelOAuthSessionRes, error)
	// CreateMyAPIKey invokes createMyAPIKey operation.
	//
	// Создаёт ключ для текущего пользователя. Полное
	// значение возвращается только в ответе `201` и в БД не
	// хранится.
	//
	// POST /api/v1/me/keys
	CreateMyAPIKey(ctx context.Context, request *CreateAPIKeyRequest) (CreateMyAPIKeyRes, error)
	// CreateProviderAPIKeys invokes createProviderAPIKeys operation.
	//
	// Регистрирует до 100 статических upstream credentials через public
	// SDK manager. Каждый credential шифруется в Store и записывается в
	// admin audit log; ключи не возвращаются.
	//
	// POST /api/v1/admin/providers/keys
	CreateProviderAPIKeys(ctx context.Context, request *CreateProviderKeysRequest) (CreateProviderAPIKeysRes, error)
	// DeleteModelOverride invokes deleteModelOverride operation.
	//
	// Удаление записывается в admin audit log.
	//
	// DELETE /api/v1/admin/models/{modelAlias}
	DeleteModelOverride(ctx context.Context, params DeleteModelOverrideParams) error
	// ExportOAuthCredential invokes exportOAuthCredential operation.
	//
	// Отдаёт attachment с полным OAuth credential JSON. Файл содержит
	// access/refresh tokens и должен обрабатываться как секрет;
	// действие записывается в admin audit log.
	//
	// GET /api/v1/admin/oauth/accounts/{accountID}/export
	ExportOAuthCredential(ctx context.Context, params ExportOAuthCredentialParams) (ExportOAuthCredentialRes, error)
	// GetMyUsage invokes getMyUsage operation.
	//
	// Возвращает агрегаты только текущего пользователя.
	// Если `from` и `to` не переданы, используется последние 30
	// дней.
	//
	// GET /api/v1/me/usage
	GetMyUsage(ctx context.Context, params GetMyUsageParams) (GetMyUsageRes, error)
	// GetOAuthSession invokes getOAuthSession operation.
	//
	// Возвращает статус OAuth-flow без PKCE verifier и device code.
	//
	// GET /api/v1/admin/oauth/sessions/{state}
	GetOAuthSession(ctx context.Context, params GetOAuthSessionParams) (GetOAuthSessionRes, error)
	// GetUpstreamAccountQuota invokes getUpstreamAccountQuota operation.
	//
	// Возвращает реактивный quota snapshot ядра и, для Antigravity,
	// последний public credits hint. `unknown=true` означает отсутствие
	// наблюдавшихся inference quota-данных, а не доступность квоты.
	//
	// GET /api/v1/admin/accounts/{accountID}/quota
	GetUpstreamAccountQuota(ctx context.Context, params GetUpstreamAccountQuotaParams) (GetUpstreamAccountQuotaRes, error)
	// Healthz invokes healthz operation.
	//
	// Возвращает 200, если процесс жив. Не проверяет БД.
	//
	// GET /healthz
	Healthz(ctx context.Context) (HealthzOK, error)
	// ImportOAuthCredential invokes importOAuthCredential operation.
	//
	// Импортирует один полный OAuth credential JSON. Дубликат
	// `provider+email` отклоняется; внешний ID игнорируется, новый ID
	// назначает coreauth.Manager. Действие пишется в admin audit log без
	// токенов.
	//
	// POST /api/v1/admin/oauth/import
	ImportOAuthCredential(ctx context.Context, request *OAuthCredential) (ImportOAuthCredentialRes, error)
	// ListAllAPIKeys invokes listAllAPIKeys operation.
	//
	// Возвращает безопасные metadata ключей и их владельцев.
	// Полные ключи и bcrypt-хэши не раскрываются.
	//
	// GET /api/v1/admin/keys
	ListAllAPIKeys(ctx context.Context) (ListAllAPIKeysRes, error)
	// ListModelOverrides invokes listModelOverrides operation.
	//
	// Возвращает allow-list и provider selection metadata моделей. Поле
	// upstream_model хранит desired mapping до появления публичного SDK hook
	// для rewrite downstream model.
	//
	// GET /api/v1/admin/models
	ListModelOverrides(ctx context.Context) (*ModelOverrideListResponse, error)
	// ListMyAPIKeys invokes listMyAPIKeys operation.
	//
	// Возвращает только безопасные метаданные ключей
	// текущего пользователя. Полный ключ и bcrypt-хэш не
	// раскрываются.
	//
	// GET /api/v1/me/keys
	ListMyAPIKeys(ctx context.Context) (ListMyAPIKeysRes, error)
	// ListPendingOAuthSessions invokes listPendingOAuthSessions operation.
	//
	// Возвращает pending OAuth-сессии без PKCE verifier и device code.
	//
	// GET /api/v1/admin/oauth/sessions
	ListPendingOAuthSessions(ctx context.Context) (ListPendingOAuthSessionsRes, error)
	// ListUsers invokes listUsers operation.
	//
	// Доступно только администратору через session-cookie.
	//
	// GET /api/v1/admin/users
	ListUsers(ctx context.Context) (ListUsersRes, error)
	// Login invokes login operation.
	//
	// Проверяет credentials через LDAP либо static source согласно `auth.mode`.
	// В ответ устанавливает opaque cookie; session-token не
	// возвращается в JSON.
	//
	// POST /api/v1/login
	Login(ctx context.Context, request *LoginRequest) (LoginRes, error)
	// Metrics invokes metrics operation.
	//
	// Метрики в Prometheus exposition format (R6.5).
	//
	// GET /metrics
	Metrics(ctx context.Context) (MetricsOK, error)
	// OpenapiJson invokes openapiJson operation.
	//
	// Отдаёт текущую OpenAPI 3.1 спецификацию сервиса (R11.4).
	// Генерируется из openapi.yaml (может быть embed-нута в
	// бинарник).
	//
	// GET /openapi.json
	OpenapiJson(ctx context.Context) error
	// Readyz invokes readyz operation.
	//
	// Возвращает 200, если сервис готов принимать трафик (DB
	// ping успешен).
	// Используется k8s readiness-probe (R6.3).
	//
	// GET /readyz
	Readyz(ctx context.Context) (ReadyzRes, error)
	// RevokeMyAPIKey invokes revokeMyAPIKey operation.
	//
	// Отзывает ключ, принадлежащий текущему пользователю.
	//
	// DELETE /api/v1/me/keys/{keyID}
	RevokeMyAPIKey(ctx context.Context, params RevokeMyAPIKeyParams) (RevokeMyAPIKeyRes, error)
	// SetUserStatus invokes setUserStatus operation.
	//
	// Блокировка инвалидирует сессии пользователя. Каждое
	// изменение записывается в admin audit log.
	//
	// PATCH /api/v1/admin/users/{userID}
	SetUserStatus(ctx context.Context, request *SetUserStatusRequest, params SetUserStatusParams) (SetUserStatusRes, error)
	// TestUpstreamAccount invokes testUpstreamAccount operation.
	//
	// Проверяет OAuth через refresh-token либо API-key через metadata endpoint
	// провайдера. Inference и CountTokens не вызываются; невалидная
	// credential возвращает `200` с `valid=false`.
	//
	// POST /api/v1/admin/accounts/{accountID}/test
	TestUpstreamAccount(ctx context.Context, params TestUpstreamAccountParams) (TestUpstreamAccountRes, error)
	// UpsertModelOverride invokes upsertModelOverride operation.
	//
	// Изменение записывается в admin audit log.
	//
	// PUT /api/v1/admin/models/{modelAlias}
	UpsertModelOverride(ctx context.Context, request *UpsertModelOverrideRequest, params UpsertModelOverrideParams) (*ModelOverride, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	sec       SecuritySource
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, sec SecuritySource, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		sec:        sec,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// CancelOAuthSession invokes cancelOAuthSession operation.
//
// Отменяет pending OAuth-flow и записывает действие в admin audit log.
//
// DELETE /api/v1/admin/oauth/sessions/{state}
func (c *Client) CancelOAuthSession(ctx context.Context, params CancelOAuthSessionParams) (CancelOAuthSessionRes, error) {
	res, err := c.sendCancelOAuthSession(ctx, params)
	return res, err
}

func (c *Client) sendCancelOAuthSession(ctx context.Context, params CancelOAuthSessionParams) (res CancelOAuthSessionRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("cancelOAuthSession"),
		semconv.HTTPRequestMethodKey.String("DELETE"),
		semconv.URLTemplateKey.String("/api/v1/admin/oauth/sessions/{state}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, CancelOAuthSessionOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/api/v1/admin/oauth/sessions/"
	{
		// Encode "state" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "state",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.State))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, CancelOAuthSessionOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeCancelOAuthSessionResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CreateMyAPIKey invokes createMyAPIKey operation.
//
// Создаёт ключ для текущего пользователя. Полное
// значение возвращается только в ответе `201` и в БД не
// хранится.
//
// POST /api/v1/me/keys
func (c *Client) CreateMyAPIKey(ctx context.Context, request *CreateAPIKeyRequest) (CreateMyAPIKeyRes, error) {
	res, err := c.sendCreateMyAPIKey(ctx, request)
	return res, err
}

func (c *Client) sendCreateMyAPIKey(ctx context.Context, request *CreateAPIKeyRequest) (res CreateMyAPIKeyRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("createMyAPIKey"),
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.URLTemplateKey.String("/api/v1/me/keys"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, CreateMyAPIKeyOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/me/keys"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateMyAPIKeyRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, CreateMyAPIKeyOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeCreateMyAPIKeyResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CreateProviderAPIKeys invokes createProviderAPIKeys operation.
//
// Регистрирует до 100 статических upstream credentials через public
// SDK manager. Каждый credential шифруется в Store и записывается в
// admin audit log; ключи не возвращаются.
//
// POST /api/v1/admin/providers/keys
func (c *Client) CreateProviderAPIKeys(ctx context.Context, request *CreateProviderKeysRequest) (CreateProviderAPIKeysRes, error) {
	res, err := c.sendCreateProviderAPIKeys(ctx, request)
	return res, err
}

func (c *Client) sendCreateProviderAPIKeys(ctx context.Context, request *CreateProviderKeysRequest) (res CreateProviderAPIKeysRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("createProviderAPIKeys"),
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.URLTemplateKey.String("/api/v1/admin/providers/keys"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, CreateProviderAPIKeysOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/admin/providers/keys"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateProviderAPIKeysRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, CreateProviderAPIKeysOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeCreateProviderAPIKeysResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteModelOverride invokes deleteModelOverride operation.
//
// Удаление записывается в admin audit log.
//
// DELETE /api/v1/admin/models/{modelAlias}
func (c *Client) DeleteModelOverride(ctx context.Context, params DeleteModelOverrideParams) error {
	_, err := c.sendDeleteModelOverride(ctx, params)
	return err
}

func (c *Client) sendDeleteModelOverride(ctx context.Context, params DeleteModelOverrideParams) (res *DeleteModelOverrideNoContent, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("deleteModelOverride"),
		semconv.HTTPRequestMethodKey.String("DELETE"),
		semconv.URLTemplateKey.String("/api/v1/admin/models/{modelAlias}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, DeleteModelOverrideOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/api/v1/admin/models/"
	{
		// Encode "modelAlias" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "modelAlias",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ModelAlias))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, DeleteModelOverrideOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeDeleteModelOverrideResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ExportOAuthCredential invokes exportOAuthCredential operation.
//
// Отдаёт attachment с полным OAuth credential JSON. Файл содержит
// access/refresh tokens и должен обрабатываться как секрет;
// действие записывается в admin audit log.
//
// GET /api/v1/admin/oauth/accounts/{accountID}/export
func (c *Client) ExportOAuthCredential(ctx context.Context, params ExportOAuthCredentialParams) (ExportOAuthCredentialRes, error) {
	res, err := c.sendExportOAuthCredential(ctx, params)
	return res, err
}

func (c *Client) sendExportOAuthCredential(ctx context.Context, params ExportOAuthCredentialParams) (res ExportOAuthCredentialRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("exportOAuthCredential"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/admin/oauth/accounts/{accountID}/export"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ExportOAuthCredentialOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/api/v1/admin/oauth/accounts/"
	{
		// Encode "accountID" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "accountID",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.AccountID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/export"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, ExportOAuthCredentialOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeExportOAuthCredentialResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetMyUsage invokes getMyUsage operation.
//
// Возвращает агрегаты только текущего пользователя.
// Если `from` и `to` не переданы, используется последние 30
// дней.
//
// GET /api/v1/me/usage
func (c *Client) GetMyUsage(ctx context.Context, params GetMyUsageParams) (GetMyUsageRes, error) {
	res, err := c.sendGetMyUsage(ctx, params)
	return res, err
}

func (c *Client) sendGetMyUsage(ctx context.Context, params GetMyUsageParams) (res GetMyUsageRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getMyUsage"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/me/usage"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetMyUsageOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/me/usage"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeQueryParams"
	q := uri.NewQueryEncoder()
	{
		// Encode "from" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "from",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.From.Get(); ok {
				return e.EncodeValue(conv.DateTimeToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "to" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "to",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.To.Get(); ok {
				return e.EncodeValue(conv.DateTimeToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, GetMyUsageOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeGetMyUsageResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetOAuthSession invokes getOAuthSession operation.
//
// Возвращает статус OAuth-flow без PKCE verifier и device code.
//
// GET /api/v1/admin/oauth/sessions/{state}
func (c *Client) GetOAuthSession(ctx context.Context, params GetOAuthSessionParams) (GetOAuthSessionRes, error) {
	res, err := c.sendGetOAuthSession(ctx, params)
	return res, err
}

func (c *Client) sendGetOAuthSession(ctx context.Context, params GetOAuthSessionParams) (res GetOAuthSessionRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getOAuthSession"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/admin/oauth/sessions/{state}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetOAuthSessionOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/api/v1/admin/oauth/sessions/"
	{
		// Encode "state" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "state",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.State))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, GetOAuthSessionOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeGetOAuthSessionResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetUpstreamAccountQuota invokes getUpstreamAccountQuota operation.
//
// Возвращает реактивный quota snapshot ядра и, для Antigravity,
// последний public credits hint. `unknown=true` означает отсутствие
// наблюдавшихся inference quota-данных, а не доступность квоты.
//
// GET /api/v1/admin/accounts/{accountID}/quota
func (c *Client) GetUpstreamAccountQuota(ctx context.Context, params GetUpstreamAccountQuotaParams) (GetUpstreamAccountQuotaRes, error) {
	res, err := c.sendGetUpstreamAccountQuota(ctx, params)
	return res, err
}

func (c *Client) sendGetUpstreamAccountQuota(ctx context.Context, params GetUpstreamAccountQuotaParams) (res GetUpstreamAccountQuotaRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getUpstreamAccountQuota"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/admin/accounts/{accountID}/quota"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetUpstreamAccountQuotaOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/api/v1/admin/accounts/"
	{
		// Encode "accountID" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "accountID",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.AccountID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/quota"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, GetUpstreamAccountQuotaOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeGetUpstreamAccountQuotaResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// Healthz invokes healthz operation.
//
// Возвращает 200, если процесс жив. Не проверяет БД.
//
// GET /healthz
func (c *Client) Healthz(ctx context.Context) (HealthzOK, error) {
	res, err := c.sendHealthz(ctx)
	return res, err
}

func (c *Client) sendHealthz(ctx context.Context) (res HealthzOK, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("healthz"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/healthz"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, HealthzOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/healthz"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeHealthzResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ImportOAuthCredential invokes importOAuthCredential operation.
//
// Импортирует один полный OAuth credential JSON. Дубликат
// `provider+email` отклоняется; внешний ID игнорируется, новый ID
// назначает coreauth.Manager. Действие пишется в admin audit log без
// токенов.
//
// POST /api/v1/admin/oauth/import
func (c *Client) ImportOAuthCredential(ctx context.Context, request *OAuthCredential) (ImportOAuthCredentialRes, error) {
	res, err := c.sendImportOAuthCredential(ctx, request)
	return res, err
}

func (c *Client) sendImportOAuthCredential(ctx context.Context, request *OAuthCredential) (res ImportOAuthCredentialRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("importOAuthCredential"),
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.URLTemplateKey.String("/api/v1/admin/oauth/import"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ImportOAuthCredentialOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/admin/oauth/import"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeImportOAuthCredentialRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, ImportOAuthCredentialOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeImportOAuthCredentialResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListAllAPIKeys invokes listAllAPIKeys operation.
//
// Возвращает безопасные metadata ключей и их владельцев.
// Полные ключи и bcrypt-хэши не раскрываются.
//
// GET /api/v1/admin/keys
func (c *Client) ListAllAPIKeys(ctx context.Context) (ListAllAPIKeysRes, error) {
	res, err := c.sendListAllAPIKeys(ctx)
	return res, err
}

func (c *Client) sendListAllAPIKeys(ctx context.Context) (res ListAllAPIKeysRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("listAllAPIKeys"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/admin/keys"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ListAllAPIKeysOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/admin/keys"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, ListAllAPIKeysOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeListAllAPIKeysResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListModelOverrides invokes listModelOverrides operation.
//
// Возвращает allow-list и provider selection metadata моделей. Поле
// upstream_model хранит desired mapping до появления публичного SDK hook
// для rewrite downstream model.
//
// GET /api/v1/admin/models
func (c *Client) ListModelOverrides(ctx context.Context) (*ModelOverrideListResponse, error) {
	res, err := c.sendListModelOverrides(ctx)
	return res, err
}

func (c *Client) sendListModelOverrides(ctx context.Context) (res *ModelOverrideListResponse, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("listModelOverrides"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/admin/models"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ListModelOverridesOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/admin/models"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, ListModelOverridesOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeListModelOverridesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListMyAPIKeys invokes listMyAPIKeys operation.
//
// Возвращает только безопасные метаданные ключей
// текущего пользователя. Полный ключ и bcrypt-хэш не
// раскрываются.
//
// GET /api/v1/me/keys
func (c *Client) ListMyAPIKeys(ctx context.Context) (ListMyAPIKeysRes, error) {
	res, err := c.sendListMyAPIKeys(ctx)
	return res, err
}

func (c *Client) sendListMyAPIKeys(ctx context.Context) (res ListMyAPIKeysRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("listMyAPIKeys"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/me/keys"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ListMyAPIKeysOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/me/keys"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, ListMyAPIKeysOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeListMyAPIKeysResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListPendingOAuthSessions invokes listPendingOAuthSessions operation.
//
// Возвращает pending OAuth-сессии без PKCE verifier и device code.
//
// GET /api/v1/admin/oauth/sessions
func (c *Client) ListPendingOAuthSessions(ctx context.Context) (ListPendingOAuthSessionsRes, error) {
	res, err := c.sendListPendingOAuthSessions(ctx)
	return res, err
}

func (c *Client) sendListPendingOAuthSessions(ctx context.Context) (res ListPendingOAuthSessionsRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("listPendingOAuthSessions"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/admin/oauth/sessions"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ListPendingOAuthSessionsOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/admin/oauth/sessions"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, ListPendingOAuthSessionsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeListPendingOAuthSessionsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListUsers invokes listUsers operation.
//
// Доступно только администратору через session-cookie.
//
// GET /api/v1/admin/users
func (c *Client) ListUsers(ctx context.Context) (ListUsersRes, error) {
	res, err := c.sendListUsers(ctx)
	return res, err
}

func (c *Client) sendListUsers(ctx context.Context) (res ListUsersRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("listUsers"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/admin/users"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ListUsersOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/admin/users"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, ListUsersOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeListUsersResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// Login invokes login operation.
//
// Проверяет credentials через LDAP либо static source согласно `auth.mode`.
// В ответ устанавливает opaque cookie; session-token не
// возвращается в JSON.
//
// POST /api/v1/login
func (c *Client) Login(ctx context.Context, request *LoginRequest) (LoginRes, error) {
	res, err := c.sendLogin(ctx, request)
	return res, err
}

func (c *Client) sendLogin(ctx context.Context, request *LoginRequest) (res LoginRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("login"),
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.URLTemplateKey.String("/api/v1/login"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, LoginOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/login"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeLoginRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeLoginResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// Metrics invokes metrics operation.
//
// Метрики в Prometheus exposition format (R6.5).
//
// GET /metrics
func (c *Client) Metrics(ctx context.Context) (MetricsOK, error) {
	res, err := c.sendMetrics(ctx)
	return res, err
}

func (c *Client) sendMetrics(ctx context.Context) (res MetricsOK, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("metrics"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/metrics"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, MetricsOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/metrics"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeMetricsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// OpenapiJson invokes openapiJson operation.
//
// Отдаёт текущую OpenAPI 3.1 спецификацию сервиса (R11.4).
// Генерируется из openapi.yaml (может быть embed-нута в
// бинарник).
//
// GET /openapi.json
func (c *Client) OpenapiJson(ctx context.Context) error {
	_, err := c.sendOpenapiJson(ctx)
	return err
}

func (c *Client) sendOpenapiJson(ctx context.Context) (res *OpenapiJsonOK, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("openapiJson"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/openapi.json"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, OpenapiJsonOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/openapi.json"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeOpenapiJsonResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// Readyz invokes readyz operation.
//
// Возвращает 200, если сервис готов принимать трафик (DB
// ping успешен).
// Используется k8s readiness-probe (R6.3).
//
// GET /readyz
func (c *Client) Readyz(ctx context.Context) (ReadyzRes, error) {
	res, err := c.sendReadyz(ctx)
	return res, err
}

func (c *Client) sendReadyz(ctx context.Context) (res ReadyzRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("readyz"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/readyz"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ReadyzOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/readyz"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeReadyzResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// RevokeMyAPIKey invokes revokeMyAPIKey operation.
//
// Отзывает ключ, принадлежащий текущему пользователю.
//
// DELETE /api/v1/me/keys/{keyID}
func (c *Client) RevokeMyAPIKey(ctx context.Context, params RevokeMyAPIKeyParams) (RevokeMyAPIKeyRes, error) {
	res, err := c.sendRevokeMyAPIKey(ctx, params)
	return res, err
}

func (c *Client) sendRevokeMyAPIKey(ctx context.Context, params RevokeMyAPIKeyParams) (res RevokeMyAPIKeyRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("revokeMyAPIKey"),
		semconv.HTTPRequestMethodKey.String("DELETE"),
		semconv.URLTemplateKey.String("/api/v1/me/keys/{keyID}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, RevokeMyAPIKeyOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/api/v1/me/keys/"
	{
		// Encode "keyID" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "keyID",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.KeyID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, RevokeMyAPIKeyOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeRevokeMyAPIKeyResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SetUserStatus invokes setUserStatus operation.
//
// Блокировка инвалидирует сессии пользователя. Каждое
// изменение записывается в admin audit log.
//
// PATCH /api/v1/admin/users/{userID}
func (c *Client) SetUserStatus(ctx context.Context, request *SetUserStatusRequest, params SetUserStatusParams) (SetUserStatusRes, error) {
	res, err := c.sendSetUserStatus(ctx, request, params)
	return res, err
}

func (c *Client) sendSetUserStatus(ctx context.Context, request *SetUserStatusRequest, params SetUserStatusParams) (res SetUserStatusRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("setUserStatus"),
		semconv.HTTPRequestMethodKey.String("PATCH"),
		semconv.URLTemplateKey.String("/api/v1/admin/users/{userID}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, SetUserStatusOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/api/v1/admin/users/"
	{
		// Encode "userID" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "userID",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.Int64ToString(params.UserID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "PATCH", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSetUserStatusRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, SetUserStatusOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeSetUserStatusResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// TestUpstreamAccount invokes testUpstreamAccount operation.
//
// Проверяет OAuth через refresh-token либо API-key через metadata endpoint
// провайдера. Inference и CountTokens не вызываются; невалидная
// credential возвращает `200` с `valid=false`.
//
// POST /api/v1/admin/accounts/{accountID}/test
func (c *Client) TestUpstreamAccount(ctx context.Context, params TestUpstreamAccountParams) (TestUpstreamAccountRes, error) {
	res, err := c.sendTestUpstreamAccount(ctx, params)
	return res, err
}

func (c *Client) sendTestUpstreamAccount(ctx context.Context, params TestUpstreamAccountParams) (res TestUpstreamAccountRes, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("testUpstreamAccount"),
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.URLTemplateKey.String("/api/v1/admin/accounts/{accountID}/test"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, TestUpstreamAccountOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/api/v1/admin/accounts/"
	{
		// Encode "accountID" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "accountID",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.AccountID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/test"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, TestUpstreamAccountOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeTestUpstreamAccountResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// UpsertModelOverride invokes upsertModelOverride operation.
//
// Изменение записывается в admin audit log.
//
// PUT /api/v1/admin/models/{modelAlias}
func (c *Client) UpsertModelOverride(ctx context.Context, request *UpsertModelOverrideRequest, params UpsertModelOverrideParams) (*ModelOverride, error) {
	res, err := c.sendUpsertModelOverride(ctx, request, params)
	return res, err
}

func (c *Client) sendUpsertModelOverride(ctx context.Context, request *UpsertModelOverrideRequest, params UpsertModelOverrideParams) (res *ModelOverride, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("upsertModelOverride"),
		semconv.HTTPRequestMethodKey.String("PUT"),
		semconv.URLTemplateKey.String("/api/v1/admin/models/{modelAlias}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, UpsertModelOverrideOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/api/v1/admin/models/"
	{
		// Encode "modelAlias" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "modelAlias",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ModelAlias))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeUpsertModelOverrideRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:SessionCookie"
			switch err := c.securitySessionCookie(ctx, UpsertModelOverrideOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"SessionCookie\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeUpsertModelOverrideResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
