// Code generated by ogen, DO NOT EDIT.
package ogen

type CancelOAuthSessionRes interface {
	cancelOAuthSessionRes()
}

type CreateMyAPIKeyRes interface {
	createMyAPIKeyRes()
}

type CreateProviderAPIKeysRes interface {
	createProviderAPIKeysRes()
}

type ExportOAuthCredentialRes interface {
	exportOAuthCredentialRes()
}

type GetCurrentUserRes interface {
	getCurrentUserRes()
}

type GetMyUsageRes interface {
	getMyUsageRes()
}

type GetOAuthSessionRes interface {
	getOAuthSessionRes()
}

type GetUpstreamAccountQuotaRes interface {
	getUpstreamAccountQuotaRes()
}

type ImportOAuthCredentialRes interface {
	importOAuthCredentialRes()
}

type ListAllAPIKeysRes interface {
	listAllAPIKeysRes()
}

type ListMyAPIKeysRes interface {
	listMyAPIKeysRes()
}

type ListPendingOAuthSessionsRes interface {
	listPendingOAuthSessionsRes()
}

type ListUsersRes interface {
	listUsersRes()
}

type LoginRes interface {
	loginRes()
}

type ReadyzRes interface {
	readyzRes()
}

type RevokeMyAPIKeyRes interface {
	revokeMyAPIKeyRes()
}

type SetUserStatusRes interface {
	setUserStatusRes()
}

type TestUpstreamAccountRes interface {
	testUpstreamAccountRes()
}
