// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelOAuthSession implements cancelOAuthSession operation.
//
// Отменяет pending OAuth-flow и записывает действие в admin audit log.
//
// DELETE /api/v1/admin/oauth/sessions/{state}
func (UnimplementedHandler) CancelOAuthSession(ctx context.Context, params CancelOAuthSessionParams) (r CancelOAuthSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMyAPIKey implements createMyAPIKey operation.
//
// Создаёт ключ для текущего пользователя. Полное
// значение возвращается только в ответе `201` и в БД не
// хранится.
//
// POST /api/v1/me/keys
func (UnimplementedHandler) CreateMyAPIKey(ctx context.Context, req *CreateAPIKeyRequest) (r CreateMyAPIKeyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProviderAPIKeys implements createProviderAPIKeys operation.
//
// Регистрирует до 100 статических upstream credentials через public SDK
// manager. Каждый credential шифруется в Store и записывается в admin
// audit log; ключи не возвращаются.
//
// POST /api/v1/admin/providers/keys
func (UnimplementedHandler) CreateProviderAPIKeys(ctx context.Context, req *CreateProviderKeysRequest) (r CreateProviderAPIKeysRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteModelOverride implements deleteModelOverride operation.
//
// Удаление записывается в admin audit log.
//
// DELETE /api/v1/admin/models/{modelAlias}
func (UnimplementedHandler) DeleteModelOverride(ctx context.Context, params DeleteModelOverrideParams) error {
	return ht.ErrNotImplemented
}

// ExportOAuthCredential implements exportOAuthCredential operation.
//
// Отдаёт attachment с полным OAuth credential JSON. Файл содержит
// access/refresh tokens и должен обрабатываться как секрет;
// действие записывается в admin audit log.
//
// GET /api/v1/admin/oauth/accounts/{accountID}/export
func (UnimplementedHandler) ExportOAuthCredential(ctx context.Context, params ExportOAuthCredentialParams) (r ExportOAuthCredentialRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCurrentUser implements getCurrentUser operation.
//
// Текущий principal management-сессии.
//
// GET /api/v1/me
func (UnimplementedHandler) GetCurrentUser(ctx context.Context) (r GetCurrentUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyUsage implements getMyUsage operation.
//
// Возвращает агрегаты только текущего пользователя.
// Если `from` и `to` не переданы, используется последние 30
// дней.
//
// GET /api/v1/me/usage
func (UnimplementedHandler) GetMyUsage(ctx context.Context, params GetMyUsageParams) (r GetMyUsageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOAuthSession implements getOAuthSession operation.
//
// Возвращает статус OAuth-flow без PKCE verifier и device code.
//
// GET /api/v1/admin/oauth/sessions/{state}
func (UnimplementedHandler) GetOAuthSession(ctx context.Context, params GetOAuthSessionParams) (r GetOAuthSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUpstreamAccountQuota implements getUpstreamAccountQuota operation.
//
// Возвращает реактивный quota snapshot ядра и, для Antigravity,
// последний public credits hint. `unknown=true` означает отсутствие
// наблюдавшихся inference quota-данных, а не доступность квоты.
//
// GET /api/v1/admin/accounts/{accountID}/quota
func (UnimplementedHandler) GetUpstreamAccountQuota(ctx context.Context, params GetUpstreamAccountQuotaParams) (r GetUpstreamAccountQuotaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Healthz implements healthz operation.
//
// Возвращает 200, если процесс жив. Не проверяет БД.
//
// GET /healthz
func (UnimplementedHandler) Healthz(ctx context.Context) (r HealthzOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ImportOAuthCredential implements importOAuthCredential operation.
//
// Импортирует один полный OAuth credential JSON. Дубликат
// `provider+email` отклоняется; внешний ID игнорируется, новый ID
// назначает coreauth.Manager. Действие пишется в admin audit log без
// токенов.
//
// POST /api/v1/admin/oauth/import
func (UnimplementedHandler) ImportOAuthCredential(ctx context.Context, req *OAuthCredential) (r ImportOAuthCredentialRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAllAPIKeys implements listAllAPIKeys operation.
//
// Возвращает безопасные metadata ключей и их владельцев.
// Полные ключи и bcrypt-хэши не раскрываются.
//
// GET /api/v1/admin/keys
func (UnimplementedHandler) ListAllAPIKeys(ctx context.Context) (r ListAllAPIKeysRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListModelOverrides implements listModelOverrides operation.
//
// Возвращает allow-list и provider selection metadata моделей. Поле
// upstream_model хранит desired mapping до появления публичного SDK hook
// для rewrite downstream model.
//
// GET /api/v1/admin/models
func (UnimplementedHandler) ListModelOverrides(ctx context.Context) (r *ModelOverrideListResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMyAPIKeys implements listMyAPIKeys operation.
//
// Возвращает только безопасные метаданные ключей
// текущего пользователя. Полный ключ и bcrypt-хэш не
// раскрываются.
//
// GET /api/v1/me/keys
func (UnimplementedHandler) ListMyAPIKeys(ctx context.Context) (r ListMyAPIKeysRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPendingOAuthSessions implements listPendingOAuthSessions operation.
//
// Возвращает pending OAuth-сессии без PKCE verifier и device code.
//
// GET /api/v1/admin/oauth/sessions
func (UnimplementedHandler) ListPendingOAuthSessions(ctx context.Context) (r ListPendingOAuthSessionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUsers implements listUsers operation.
//
// Доступно только администратору через session-cookie.
//
// GET /api/v1/admin/users
func (UnimplementedHandler) ListUsers(ctx context.Context) (r ListUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Login implements login operation.
//
// Проверяет credentials через LDAP либо static source согласно `auth.mode`.
// В ответ устанавливает opaque cookie; session-token не возвращается
// в JSON.
//
// POST /api/v1/login
func (UnimplementedHandler) Login(ctx context.Context, req *LoginRequest) (r LoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Logout implements logout operation.
//
// Удаляет session-cookie, если она была передана, и всегда
// возвращает успешный ответ с инструкцией удалить cookie
// на клиенте.
//
// POST /api/v1/logout
func (UnimplementedHandler) Logout(ctx context.Context) (r *LogoutNoContent, _ error) {
	return r, ht.ErrNotImplemented
}

// Metrics implements metrics operation.
//
// Метрики в Prometheus exposition format (R6.5).
//
// GET /metrics
func (UnimplementedHandler) Metrics(ctx context.Context) (r MetricsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// OpenapiJson implements openapiJson operation.
//
// Отдаёт текущую OpenAPI 3.1 спецификацию сервиса (R11.4).
// Генерируется из openapi.yaml (может быть embed-нута в бинарник).
//
// GET /openapi.json
func (UnimplementedHandler) OpenapiJson(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// ProxyChatCompletions implements proxyChatCompletions operation.
//
// Тело и ответ прозрачно обрабатываются upstream SDK;
// бизнес-слой описывает только URL, auth и общие ошибки.
//
// POST /v1/chat/completions
func (UnimplementedHandler) ProxyChatCompletions(ctx context.Context) (r ProxyChatCompletionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProxyGenerateContent implements proxyGenerateContent operation.
//
// Тело и ответ прозрачно обрабатываются upstream SDK;
// бизнес-слой не владеет их схемами.
//
// POST /v1/models/{model}:generateContent
func (UnimplementedHandler) ProxyGenerateContent(ctx context.Context, params ProxyGenerateContentParams) (r ProxyGenerateContentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProxyMessages implements proxyMessages operation.
//
// Тело и ответ прозрачно обрабатываются upstream SDK;
// бизнес-слой не владеет их схемами.
//
// POST /v1/messages
func (UnimplementedHandler) ProxyMessages(ctx context.Context) (r ProxyMessagesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProxyModels implements proxyModels operation.
//
// Список моделей формируется upstream SDK; его схема
// намеренно не дублируется в бизнес-слое.
//
// GET /v1/models
func (UnimplementedHandler) ProxyModels(ctx context.Context) (r ProxyModelsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ProxyResponses implements proxyResponses operation.
//
// Тело и ответ прозрачно обрабатываются upstream SDK;
// бизнес-слой не владеет их схемами.
//
// POST /v1/responses
func (UnimplementedHandler) ProxyResponses(ctx context.Context) (r ProxyResponsesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Readyz implements readyz operation.
//
// Возвращает 200, если сервис готов принимать трафик (DB ping
// успешен). Используется k8s readiness-probe (R6.3).
//
// GET /readyz
func (UnimplementedHandler) Readyz(ctx context.Context) (r ReadyzRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RevokeMyAPIKey implements revokeMyAPIKey operation.
//
// Отзывает ключ, принадлежащий текущему пользователю.
//
// DELETE /api/v1/me/keys/{keyID}
func (UnimplementedHandler) RevokeMyAPIKey(ctx context.Context, params RevokeMyAPIKeyParams) (r RevokeMyAPIKeyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetUserStatus implements setUserStatus operation.
//
// Блокировка инвалидирует сессии пользователя. Каждое
// изменение записывается в admin audit log.
//
// PATCH /api/v1/admin/users/{userID}
func (UnimplementedHandler) SetUserStatus(ctx context.Context, req *SetUserStatusRequest, params SetUserStatusParams) (r SetUserStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TestUpstreamAccount implements testUpstreamAccount operation.
//
// Проверяет OAuth через refresh-token либо API-key через metadata endpoint
// провайдера. Inference и CountTokens не вызываются; невалидная
// credential возвращает `200` с `valid=false`.
//
// POST /api/v1/admin/accounts/{accountID}/test
func (UnimplementedHandler) TestUpstreamAccount(ctx context.Context, params TestUpstreamAccountParams) (r TestUpstreamAccountRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpsertModelOverride implements upsertModelOverride operation.
//
// Изменение записывается в admin audit log.
//
// PUT /api/v1/admin/models/{modelAlias}
func (UnimplementedHandler) UpsertModelOverride(ctx context.Context, req *UpsertModelOverrideRequest, params UpsertModelOverrideParams) (r *ModelOverride, _ error) {
	return r, ht.ErrNotImplemented
}
