// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_audit_log.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAdminAuditLog = `-- name: InsertAdminAuditLog :exec
INSERT INTO admin_audit_log (actor_user_id, action, target_type, target_id, details, actor_ip)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type InsertAdminAuditLogParams struct {
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	Action      string      `json:"action"`
	TargetType  pgtype.Text `json:"target_type"`
	TargetID    pgtype.Text `json:"target_id"`
	Details     []byte      `json:"details"`
	ActorIp     *netip.Addr `json:"actor_ip"`
}

func (q *Queries) InsertAdminAuditLog(ctx context.Context, arg InsertAdminAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAdminAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Details,
		arg.ActorIp,
	)
	return err
}
