// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, key_hash, key_prefix, name, expires_at, scope)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, user_id, key_prefix, name, status, expires_at, scope, last_used_at, created_at
`

type CreateAPIKeyParams struct {
	UserID    int64       `json:"user_id"`
	KeyHash   string      `json:"key_hash"`
	KeyPrefix string      `json:"key_prefix"`
	Name      pgtype.Text `json:"name"`
	ExpiresAt pgtype.Date `json:"expires_at"`
	Scope     []byte      `json:"scope"`
}

type CreateAPIKeyRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	KeyPrefix  string             `json:"key_prefix"`
	Name       pgtype.Text        `json:"name"`
	Status     string             `json:"status"`
	ExpiresAt  pgtype.Date        `json:"expires_at"`
	Scope      []byte             `json:"scope"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Name,
		arg.ExpiresAt,
		arg.Scope,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyPrefix,
		&i.Name,
		&i.Status,
		&i.ExpiresAt,
		&i.Scope,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findAPIKeyCandidates = `-- name: FindAPIKeyCandidates :many
SELECT
    api_keys.id,
    api_keys.user_id,
    api_keys.key_hash,
    api_keys.status,
    api_keys.expires_at,
    users.status AS user_status
FROM api_keys
JOIN users ON users.id = api_keys.user_id
WHERE api_keys.key_prefix = $1
  AND api_keys.status = 'active'
  AND (api_keys.expires_at IS NULL OR api_keys.expires_at >= CURRENT_DATE)
`

type FindAPIKeyCandidatesRow struct {
	ID         int64       `json:"id"`
	UserID     int64       `json:"user_id"`
	KeyHash    string      `json:"key_hash"`
	Status     string      `json:"status"`
	ExpiresAt  pgtype.Date `json:"expires_at"`
	UserStatus string      `json:"user_status"`
}

func (q *Queries) FindAPIKeyCandidates(ctx context.Context, keyPrefix string) ([]FindAPIKeyCandidatesRow, error) {
	rows, err := q.db.Query(ctx, findAPIKeyCandidates, keyPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAPIKeyCandidatesRow{}
	for rows.Next() {
		var i FindAPIKeyCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KeyHash,
			&i.Status,
			&i.ExpiresAt,
			&i.UserStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, key_prefix, name, status, expires_at, scope, last_used_at, created_at
FROM api_keys
WHERE user_id = $1
ORDER BY id DESC
`

type ListAPIKeysByUserRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	KeyPrefix  string             `json:"key_prefix"`
	Name       pgtype.Text        `json:"name"`
	Status     string             `json:"status"`
	ExpiresAt  pgtype.Date        `json:"expires_at"`
	Scope      []byte             `json:"scope"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID int64) ([]ListAPIKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysByUserRow{}
	for rows.Next() {
		var i ListAPIKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KeyPrefix,
			&i.Name,
			&i.Status,
			&i.ExpiresAt,
			&i.Scope,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys
SET status = 'revoked'
WHERE id = $1 AND user_id = $2 AND status = 'active'
`

type RevokeAPIKeyParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
