// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package dbgen

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertUsageEvents = `-- name: InsertUsageEvents :batchexec
INSERT INTO usage_events (
    user_id, api_key_id, upstream_account_id, provider, model,
    input_tokens, output_tokens, reasoning_tokens, cached_tokens, total_tokens,
    status_code, error, latency_ms, ttft_ms, failed
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15
)
`

type InsertUsageEventsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertUsageEventsParams struct {
	UserID            pgtype.Int8 `json:"user_id"`
	ApiKeyID          pgtype.Int8 `json:"api_key_id"`
	UpstreamAccountID pgtype.Text `json:"upstream_account_id"`
	Provider          pgtype.Text `json:"provider"`
	Model             pgtype.Text `json:"model"`
	InputTokens       int32       `json:"input_tokens"`
	OutputTokens      int32       `json:"output_tokens"`
	ReasoningTokens   int32       `json:"reasoning_tokens"`
	CachedTokens      int32       `json:"cached_tokens"`
	TotalTokens       int32       `json:"total_tokens"`
	StatusCode        int32       `json:"status_code"`
	Error             pgtype.Text `json:"error"`
	LatencyMs         int32       `json:"latency_ms"`
	TtftMs            int32       `json:"ttft_ms"`
	Failed            bool        `json:"failed"`
}

func (q *Queries) InsertUsageEvents(ctx context.Context, arg []InsertUsageEventsParams) *InsertUsageEventsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.UserID,
			a.ApiKeyID,
			a.UpstreamAccountID,
			a.Provider,
			a.Model,
			a.InputTokens,
			a.OutputTokens,
			a.ReasoningTokens,
			a.CachedTokens,
			a.TotalTokens,
			a.StatusCode,
			a.Error,
			a.LatencyMs,
			a.TtftMs,
			a.Failed,
		}
		batch.Queue(insertUsageEvents, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertUsageEventsBatchResults{br, len(arg), false}
}

func (b *InsertUsageEventsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertUsageEventsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
