// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAuditLog struct {
	ID          int64              `json:"id"`
	ActorUserID pgtype.Int8        `json:"actor_user_id"`
	Action      string             `json:"action"`
	TargetType  pgtype.Text        `json:"target_type"`
	TargetID    pgtype.Text        `json:"target_id"`
	Details     []byte             `json:"details"`
	ActorIp     *netip.Addr        `json:"actor_ip"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ApiKey struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	KeyHash    string             `json:"key_hash"`
	KeyPrefix  string             `json:"key_prefix"`
	Name       pgtype.Text        `json:"name"`
	Status     string             `json:"status"`
	ExpiresAt  pgtype.Date        `json:"expires_at"`
	Scope      []byte             `json:"scope"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ModelOverride struct {
	ID            int64  `json:"id"`
	Provider      string `json:"provider"`
	ModelAlias    string `json:"model_alias"`
	UpstreamModel string `json:"upstream_model"`
	Enabled       bool   `json:"enabled"`
	Config        []byte `json:"config"`
}

type ModelRegistrySnapshot struct {
	Provider  string             `json:"provider"`
	ClientID  string             `json:"client_id"`
	Models    []byte             `json:"models"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OauthSession struct {
	State        string             `json:"state"`
	Provider     string             `json:"provider"`
	FlowType     string             `json:"flow_type"`
	Status       string             `json:"status"`
	AuthID       pgtype.Text        `json:"auth_id"`
	PkceVerifier pgtype.Text        `json:"pkce_verifier"`
	DeviceCode   pgtype.Text        `json:"device_code"`
	UserCode     pgtype.Text        `json:"user_code"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RuntimeRevision struct {
	Name      string             `json:"name"`
	Revision  int64              `json:"revision"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	Role      string             `json:"role"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedIp *netip.Addr        `json:"created_ip"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UpstreamAccount struct {
	ID               string             `json:"id"`
	Provider         string             `json:"provider"`
	Email            string             `json:"email"`
	AuthType         string             `json:"auth_type"`
	Label            pgtype.Text        `json:"label"`
	CredentialsEnc   []byte             `json:"credentials_enc"`
	EncKeyVersion    int32              `json:"enc_key_version"`
	Attributes       []byte             `json:"attributes"`
	Status           string             `json:"status"`
	LastRefreshedAt  pgtype.Timestamptz `json:"last_refreshed_at"`
	NextRefreshAfter pgtype.Timestamptz `json:"next_refresh_after"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type UsageAggregate struct {
	PeriodStart     pgtype.Date `json:"period_start"`
	Dimension       string      `json:"dimension"`
	DimensionValue  string      `json:"dimension_value"`
	RequestCount    int64       `json:"request_count"`
	InputTokensSum  int64       `json:"input_tokens_sum"`
	OutputTokensSum int64       `json:"output_tokens_sum"`
	TotalTokensSum  int64       `json:"total_tokens_sum"`
	FailureCount    int64       `json:"failure_count"`
}

type UsageEvent struct {
	ID                int64              `json:"id"`
	UserID            pgtype.Int8        `json:"user_id"`
	ApiKeyID          pgtype.Int8        `json:"api_key_id"`
	UpstreamAccountID pgtype.Text        `json:"upstream_account_id"`
	Provider          pgtype.Text        `json:"provider"`
	Model             pgtype.Text        `json:"model"`
	InputTokens       int32              `json:"input_tokens"`
	OutputTokens      int32              `json:"output_tokens"`
	ReasoningTokens   int32              `json:"reasoning_tokens"`
	CachedTokens      int32              `json:"cached_tokens"`
	TotalTokens       int32              `json:"total_tokens"`
	StatusCode        int32              `json:"status_code"`
	Error             pgtype.Text        `json:"error"`
	LatencyMs         int32              `json:"latency_ms"`
	TtftMs            int32              `json:"ttft_ms"`
	Failed            bool               `json:"failed"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type UsageEvents20260713 struct {
	ID                int64              `json:"id"`
	UserID            pgtype.Int8        `json:"user_id"`
	ApiKeyID          pgtype.Int8        `json:"api_key_id"`
	UpstreamAccountID pgtype.Text        `json:"upstream_account_id"`
	Provider          pgtype.Text        `json:"provider"`
	Model             pgtype.Text        `json:"model"`
	InputTokens       int32              `json:"input_tokens"`
	OutputTokens      int32              `json:"output_tokens"`
	ReasoningTokens   int32              `json:"reasoning_tokens"`
	CachedTokens      int32              `json:"cached_tokens"`
	TotalTokens       int32              `json:"total_tokens"`
	StatusCode        int32              `json:"status_code"`
	Error             pgtype.Text        `json:"error"`
	LatencyMs         int32              `json:"latency_ms"`
	TtftMs            int32              `json:"ttft_ms"`
	Failed            bool               `json:"failed"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             int64              `json:"id"`
	Username       string             `json:"username"`
	Email          pgtype.Text        `json:"email"`
	Role           string             `json:"role"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	IdentitySource string             `json:"identity_source"`
}
