// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_overrides.sql

package dbgen

import (
	"context"
)

const deleteModelOverride = `-- name: DeleteModelOverride :execrows
DELETE FROM model_overrides
WHERE model_alias = $1
`

func (q *Queries) DeleteModelOverride(ctx context.Context, modelAlias string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteModelOverride, modelAlias)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listModelOverrides = `-- name: ListModelOverrides :many
SELECT id, provider, model_alias, upstream_model, enabled, config
FROM model_overrides
ORDER BY model_alias
`

func (q *Queries) ListModelOverrides(ctx context.Context) ([]ModelOverride, error) {
	rows, err := q.db.Query(ctx, listModelOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelOverride{}
	for rows.Next() {
		var i ModelOverride
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ModelAlias,
			&i.UpstreamModel,
			&i.Enabled,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModelOverride = `-- name: UpsertModelOverride :one
INSERT INTO model_overrides (provider, model_alias, upstream_model, enabled, config)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (model_alias) DO UPDATE SET
    provider = EXCLUDED.provider,
    upstream_model = EXCLUDED.upstream_model,
    enabled = EXCLUDED.enabled,
    config = EXCLUDED.config
RETURNING id, provider, model_alias, upstream_model, enabled, config
`

type UpsertModelOverrideParams struct {
	Provider      string `json:"provider"`
	ModelAlias    string `json:"model_alias"`
	UpstreamModel string `json:"upstream_model"`
	Enabled       bool   `json:"enabled"`
	Config        []byte `json:"config"`
}

func (q *Queries) UpsertModelOverride(ctx context.Context, arg UpsertModelOverrideParams) (ModelOverride, error) {
	row := q.db.QueryRow(ctx, upsertModelOverride,
		arg.Provider,
		arg.ModelAlias,
		arg.UpstreamModel,
		arg.Enabled,
		arg.Config,
	)
	var i ModelOverride
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ModelAlias,
		&i.UpstreamModel,
		&i.Enabled,
		&i.Config,
	)
	return i, err
}
