// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_registry_snapshots.sql

package dbgen

import (
	"context"
)

const deleteModelRegistrySnapshot = `-- name: DeleteModelRegistrySnapshot :execrows
DELETE FROM model_registry_snapshots
WHERE provider = $1 AND client_id = $2
`

type DeleteModelRegistrySnapshotParams struct {
	Provider string `json:"provider"`
	ClientID string `json:"client_id"`
}

func (q *Queries) DeleteModelRegistrySnapshot(ctx context.Context, arg DeleteModelRegistrySnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteModelRegistrySnapshot, arg.Provider, arg.ClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listModelRegistrySnapshots = `-- name: ListModelRegistrySnapshots :many
SELECT provider, client_id, models, updated_at
FROM model_registry_snapshots
ORDER BY provider, client_id
`

func (q *Queries) ListModelRegistrySnapshots(ctx context.Context) ([]ModelRegistrySnapshot, error) {
	rows, err := q.db.Query(ctx, listModelRegistrySnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelRegistrySnapshot{}
	for rows.Next() {
		var i ModelRegistrySnapshot
		if err := rows.Scan(
			&i.Provider,
			&i.ClientID,
			&i.Models,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertModelRegistrySnapshot = `-- name: UpsertModelRegistrySnapshot :exec
INSERT INTO model_registry_snapshots (provider, client_id, models)
VALUES ($1, $2, $3)
ON CONFLICT (provider, client_id) DO UPDATE SET
    models = EXCLUDED.models,
    updated_at = now()
`

type UpsertModelRegistrySnapshotParams struct {
	Provider string `json:"provider"`
	ClientID string `json:"client_id"`
	Models   []byte `json:"models"`
}

func (q *Queries) UpsertModelRegistrySnapshot(ctx context.Context, arg UpsertModelRegistrySnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertModelRegistrySnapshot, arg.Provider, arg.ClientID, arg.Models)
	return err
}
