// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_sessions.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOAuthSession = `-- name: CancelOAuthSession :execrows
UPDATE oauth_sessions SET status = 'cancelled', updated_at = now()
WHERE state = $1 AND status = 'pending'
`

func (q *Queries) CancelOAuthSession(ctx context.Context, state string) (int64, error) {
	result, err := q.db.Exec(ctx, cancelOAuthSession, state)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeOAuthSession = `-- name: CompleteOAuthSession :execrows
UPDATE oauth_sessions SET status = 'completed', auth_id = $2, error_message = NULL, updated_at = now()
WHERE state = $1 AND status = 'pending'
`

type CompleteOAuthSessionParams struct {
	State  string      `json:"state"`
	AuthID pgtype.Text `json:"auth_id"`
}

func (q *Queries) CompleteOAuthSession(ctx context.Context, arg CompleteOAuthSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeOAuthSession, arg.State, arg.AuthID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createOAuthSession = `-- name: CreateOAuthSession :exec
INSERT INTO oauth_sessions (state, provider, flow_type, pkce_verifier, device_code, user_code, expires_at)
VALUES ($1, $2, $3, $5, $6, $7, $4)
`

type CreateOAuthSessionParams struct {
	State        string             `json:"state"`
	Provider     string             `json:"provider"`
	FlowType     string             `json:"flow_type"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	PkceVerifier pgtype.Text        `json:"pkce_verifier"`
	DeviceCode   pgtype.Text        `json:"device_code"`
	UserCode     pgtype.Text        `json:"user_code"`
}

func (q *Queries) CreateOAuthSession(ctx context.Context, arg CreateOAuthSessionParams) error {
	_, err := q.db.Exec(ctx, createOAuthSession,
		arg.State,
		arg.Provider,
		arg.FlowType,
		arg.ExpiresAt,
		arg.PkceVerifier,
		arg.DeviceCode,
		arg.UserCode,
	)
	return err
}

const failOAuthSession = `-- name: FailOAuthSession :execrows
UPDATE oauth_sessions SET status = 'error', error_message = $2, updated_at = now()
WHERE state = $1 AND status = 'pending'
`

type FailOAuthSessionParams struct {
	State        string      `json:"state"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) FailOAuthSession(ctx context.Context, arg FailOAuthSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, failOAuthSession, arg.State, arg.ErrorMessage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOAuthSession = `-- name: GetOAuthSession :one
SELECT state, provider, flow_type, status, auth_id, pkce_verifier, device_code, user_code, error_message, expires_at, created_at, updated_at
FROM oauth_sessions WHERE state = $1
`

func (q *Queries) GetOAuthSession(ctx context.Context, state string) (OauthSession, error) {
	row := q.db.QueryRow(ctx, getOAuthSession, state)
	var i OauthSession
	err := row.Scan(
		&i.State,
		&i.Provider,
		&i.FlowType,
		&i.Status,
		&i.AuthID,
		&i.PkceVerifier,
		&i.DeviceCode,
		&i.UserCode,
		&i.ErrorMessage,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingOAuthSessions = `-- name: ListPendingOAuthSessions :many
SELECT state, provider, flow_type, status, auth_id, pkce_verifier, device_code, user_code, error_message, expires_at, created_at, updated_at
FROM oauth_sessions WHERE status = 'pending' ORDER BY created_at DESC
`

func (q *Queries) ListPendingOAuthSessions(ctx context.Context) ([]OauthSession, error) {
	rows, err := q.db.Query(ctx, listPendingOAuthSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthSession{}
	for rows.Next() {
		var i OauthSession
		if err := rows.Scan(
			&i.State,
			&i.Provider,
			&i.FlowType,
			&i.Status,
			&i.AuthID,
			&i.PkceVerifier,
			&i.DeviceCode,
			&i.UserCode,
			&i.ErrorMessage,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
