// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	BlockUserAndDeleteSessions(ctx context.Context, id int64) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteModelOverride(ctx context.Context, modelAlias string) (int64, error)
	DeleteSessionByTokenHashForSource(ctx context.Context, arg DeleteSessionByTokenHashForSourceParams) (int64, error)
	DeleteSessionsByUser(ctx context.Context, userID int64) error
	DeleteUpstreamAccount(ctx context.Context, id string) error
	FindAPIKeyCandidates(ctx context.Context, keyPrefix string) ([]FindAPIKeyCandidatesRow, error)
	FindAPIKeyCandidatesForSource(ctx context.Context, arg FindAPIKeyCandidatesForSourceParams) ([]FindAPIKeyCandidatesForSourceRow, error)
	GetRuntimeRevision(ctx context.Context, name string) (int64, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetSessionByTokenHashForSource(ctx context.Context, arg GetSessionByTokenHashForSourceParams) (GetSessionByTokenHashForSourceRow, error)
	GetUsageSummaryByUser(ctx context.Context, arg GetUsageSummaryByUserParams) (GetUsageSummaryByUserRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	IncrementRuntimeRevision(ctx context.Context, name string) (int64, error)
	InsertAdminAuditLog(ctx context.Context, arg InsertAdminAuditLogParams) error
	InsertUsageEvent(ctx context.Context, arg InsertUsageEventParams) error
	ListAPIKeysByUser(ctx context.Context, userID int64) ([]ListAPIKeysByUserRow, error)
	ListModelOverrides(ctx context.Context) ([]ModelOverride, error)
	ListUpstreamAccounts(ctx context.Context) ([]UpstreamAccount, error)
	ListUsageByAPIKeyForUser(ctx context.Context, arg ListUsageByAPIKeyForUserParams) ([]ListUsageByAPIKeyForUserRow, error)
	ListUsageByModelForUser(ctx context.Context, arg ListUsageByModelForUserParams) ([]ListUsageByModelForUserRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) (int64, error)
	UpsertModelOverride(ctx context.Context, arg UpsertModelOverrideParams) (ModelOverride, error)
	UpsertStaticUser(ctx context.Context, arg UpsertStaticUserParams) (UpsertStaticUserRow, error)
	UpsertUpstreamAccount(ctx context.Context, arg UpsertUpstreamAccountParams) (string, error)
	UpsertUserFromLDAP(ctx context.Context, arg UpsertUserFromLDAPParams) (UpsertUserFromLDAPRow, error)
}

var _ Querier = (*Queries)(nil)
