// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_revisions.sql

package dbgen

import (
	"context"
)

const getRuntimeRevision = `-- name: GetRuntimeRevision :one
SELECT revision
FROM runtime_revisions
WHERE name = $1
`

func (q *Queries) GetRuntimeRevision(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, getRuntimeRevision, name)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const incrementRuntimeRevision = `-- name: IncrementRuntimeRevision :one
UPDATE runtime_revisions
SET revision = revision + 1, updated_at = now()
WHERE name = $1
RETURNING revision
`

func (q *Queries) IncrementRuntimeRevision(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, incrementRuntimeRevision, name)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}
