// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, role, expires_at, created_ip)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, token_hash, role, expires_at, created_ip, created_at
`

type CreateSessionParams struct {
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	Role      string             `json:"role"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedIp *netip.Addr        `json:"created_ip"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.Role,
		arg.ExpiresAt,
		arg.CreatedIp,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedIp,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionsByUser = `-- name: DeleteSessionsByUser :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUser, userID)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    sessions.id,
    sessions.user_id,
    sessions.token_hash,
    sessions.role,
    sessions.expires_at,
    sessions.created_ip,
    sessions.created_at,
    users.status AS user_status
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND sessions.expires_at > now()
`

type GetSessionByTokenHashRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	Role       string             `json:"role"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedIp  *netip.Addr        `json:"created_ip"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UserStatus string             `json:"user_status"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedIp,
		&i.CreatedAt,
		&i.UserStatus,
	)
	return i, err
}

const getSessionByTokenHashForSource = `-- name: GetSessionByTokenHashForSource :one
SELECT
    sessions.id,
    sessions.user_id,
    sessions.token_hash,
    sessions.role,
    sessions.expires_at,
    sessions.created_ip,
    sessions.created_at,
    users.status AS user_status
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND users.identity_source = $2
  AND sessions.expires_at > now()
`

type GetSessionByTokenHashForSourceParams struct {
	TokenHash      string `json:"token_hash"`
	IdentitySource string `json:"identity_source"`
}

type GetSessionByTokenHashForSourceRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	Role       string             `json:"role"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedIp  *netip.Addr        `json:"created_ip"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UserStatus string             `json:"user_status"`
}

func (q *Queries) GetSessionByTokenHashForSource(ctx context.Context, arg GetSessionByTokenHashForSourceParams) (GetSessionByTokenHashForSourceRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHashForSource, arg.TokenHash, arg.IdentitySource)
	var i GetSessionByTokenHashForSourceRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedIp,
		&i.CreatedAt,
		&i.UserStatus,
	)
	return i, err
}
