// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upstream_accounts.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUpstreamAccount = `-- name: DeleteUpstreamAccount :exec
DELETE FROM upstream_accounts
WHERE id = $1
`

func (q *Queries) DeleteUpstreamAccount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUpstreamAccount, id)
	return err
}

const listUpstreamAccounts = `-- name: ListUpstreamAccounts :many
SELECT
    id,
    provider,
    email,
    auth_type,
    label,
    credentials_enc,
    enc_key_version,
    attributes,
    status,
    last_refreshed_at,
    next_refresh_after,
    created_at
FROM upstream_accounts
ORDER BY id
`

func (q *Queries) ListUpstreamAccounts(ctx context.Context) ([]UpstreamAccount, error) {
	rows, err := q.db.Query(ctx, listUpstreamAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UpstreamAccount{}
	for rows.Next() {
		var i UpstreamAccount
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Email,
			&i.AuthType,
			&i.Label,
			&i.CredentialsEnc,
			&i.EncKeyVersion,
			&i.Attributes,
			&i.Status,
			&i.LastRefreshedAt,
			&i.NextRefreshAfter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUpstreamAccount = `-- name: UpsertUpstreamAccount :one
INSERT INTO upstream_accounts (
    id,
    provider,
    email,
    auth_type,
    label,
    credentials_enc,
    enc_key_version,
    attributes,
    status,
    last_refreshed_at,
    next_refresh_after
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
ON CONFLICT (id) DO UPDATE SET
    provider = EXCLUDED.provider,
    email = EXCLUDED.email,
    auth_type = EXCLUDED.auth_type,
    label = EXCLUDED.label,
    credentials_enc = EXCLUDED.credentials_enc,
    enc_key_version = EXCLUDED.enc_key_version,
    attributes = EXCLUDED.attributes,
    status = EXCLUDED.status,
    last_refreshed_at = EXCLUDED.last_refreshed_at,
    next_refresh_after = EXCLUDED.next_refresh_after
RETURNING id
`

type UpsertUpstreamAccountParams struct {
	ID               string             `json:"id"`
	Provider         string             `json:"provider"`
	Email            string             `json:"email"`
	AuthType         string             `json:"auth_type"`
	Label            pgtype.Text        `json:"label"`
	CredentialsEnc   []byte             `json:"credentials_enc"`
	EncKeyVersion    int32              `json:"enc_key_version"`
	Attributes       []byte             `json:"attributes"`
	Status           string             `json:"status"`
	LastRefreshedAt  pgtype.Timestamptz `json:"last_refreshed_at"`
	NextRefreshAfter pgtype.Timestamptz `json:"next_refresh_after"`
}

func (q *Queries) UpsertUpstreamAccount(ctx context.Context, arg UpsertUpstreamAccountParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertUpstreamAccount,
		arg.ID,
		arg.Provider,
		arg.Email,
		arg.AuthType,
		arg.Label,
		arg.CredentialsEnc,
		arg.EncKeyVersion,
		arg.Attributes,
		arg.Status,
		arg.LastRefreshedAt,
		arg.NextRefreshAfter,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
