// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_events.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertUsageEvent = `-- name: InsertUsageEvent :exec
INSERT INTO usage_events (
    user_id, api_key_id, upstream_account_id, provider, model,
    input_tokens, output_tokens, reasoning_tokens, cached_tokens, total_tokens,
    status_code, error, latency_ms, ttft_ms, failed
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15
)
`

type InsertUsageEventParams struct {
	UserID            pgtype.Int8 `json:"user_id"`
	ApiKeyID          pgtype.Int8 `json:"api_key_id"`
	UpstreamAccountID pgtype.Text `json:"upstream_account_id"`
	Provider          pgtype.Text `json:"provider"`
	Model             pgtype.Text `json:"model"`
	InputTokens       int32       `json:"input_tokens"`
	OutputTokens      int32       `json:"output_tokens"`
	ReasoningTokens   int32       `json:"reasoning_tokens"`
	CachedTokens      int32       `json:"cached_tokens"`
	TotalTokens       int32       `json:"total_tokens"`
	StatusCode        int32       `json:"status_code"`
	Error             pgtype.Text `json:"error"`
	LatencyMs         int32       `json:"latency_ms"`
	TtftMs            int32       `json:"ttft_ms"`
	Failed            bool        `json:"failed"`
}

func (q *Queries) InsertUsageEvent(ctx context.Context, arg InsertUsageEventParams) error {
	_, err := q.db.Exec(ctx, insertUsageEvent,
		arg.UserID,
		arg.ApiKeyID,
		arg.UpstreamAccountID,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.ReasoningTokens,
		arg.CachedTokens,
		arg.TotalTokens,
		arg.StatusCode,
		arg.Error,
		arg.LatencyMs,
		arg.TtftMs,
		arg.Failed,
	)
	return err
}
