// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockUserAndDeleteSessions = `-- name: BlockUserAndDeleteSessions :one
WITH blocked AS (
    UPDATE users
    SET status = 'blocked', updated_at = now()
    WHERE users.id = $1
    RETURNING users.id
), deleted_sessions AS (
    DELETE FROM sessions
    WHERE sessions.user_id IN (SELECT blocked.id FROM blocked)
    RETURNING sessions.id
)
SELECT count(*) FROM blocked
`

func (q *Queries) BlockUserAndDeleteSessions(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, blockUserAndDeleteSessions, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, role, status, identity_source, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID             int64              `json:"id"`
	Username       string             `json:"username"`
	Email          pgtype.Text        `json:"email"`
	Role           string             `json:"role"`
	Status         string             `json:"status"`
	IdentitySource string             `json:"identity_source"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.IdentitySource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, role, status, identity_source, created_at, updated_at
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID             int64              `json:"id"`
	Username       string             `json:"username"`
	Email          pgtype.Text        `json:"email"`
	Role           string             `json:"role"`
	Status         string             `json:"status"`
	IdentitySource string             `json:"identity_source"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.IdentitySource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserStatus = `-- name: SetUserStatus :execrows
UPDATE users
SET status = $1, updated_at = now()
WHERE id = $2
`

type SetUserStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertStaticUser = `-- name: UpsertStaticUser :one
INSERT INTO users (username, email, role, identity_source)
VALUES ($1, $2, $3, 'static')
ON CONFLICT (username) DO UPDATE SET
    email = EXCLUDED.email,
    role = EXCLUDED.role,
    updated_at = now()
RETURNING id, username, email, role, status, identity_source, created_at, updated_at
`

type UpsertStaticUserParams struct {
	Username string      `json:"username"`
	Email    pgtype.Text `json:"email"`
	Role     string      `json:"role"`
}

type UpsertStaticUserRow struct {
	ID             int64              `json:"id"`
	Username       string             `json:"username"`
	Email          pgtype.Text        `json:"email"`
	Role           string             `json:"role"`
	Status         string             `json:"status"`
	IdentitySource string             `json:"identity_source"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertStaticUser(ctx context.Context, arg UpsertStaticUserParams) (UpsertStaticUserRow, error) {
	row := q.db.QueryRow(ctx, upsertStaticUser, arg.Username, arg.Email, arg.Role)
	var i UpsertStaticUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.IdentitySource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserFromLDAP = `-- name: UpsertUserFromLDAP :one
INSERT INTO users (username, email, role, identity_source)
VALUES ($1, $2, $3, 'ldap')
ON CONFLICT (username) DO UPDATE SET
    email = EXCLUDED.email,
    role = EXCLUDED.role,
    updated_at = now()
RETURNING id, username, email, role, status, identity_source, created_at, updated_at
`

type UpsertUserFromLDAPParams struct {
	Username string      `json:"username"`
	Email    pgtype.Text `json:"email"`
	Role     string      `json:"role"`
}

type UpsertUserFromLDAPRow struct {
	ID             int64              `json:"id"`
	Username       string             `json:"username"`
	Email          pgtype.Text        `json:"email"`
	Role           string             `json:"role"`
	Status         string             `json:"status"`
	IdentitySource string             `json:"identity_source"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertUserFromLDAP(ctx context.Context, arg UpsertUserFromLDAPParams) (UpsertUserFromLDAPRow, error) {
	row := q.db.QueryRow(ctx, upsertUserFromLDAP, arg.Username, arg.Email, arg.Role)
	var i UpsertUserFromLDAPRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.IdentitySource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
