// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockUserAndDeleteSessions = `-- name: BlockUserAndDeleteSessions :one
WITH blocked AS (
    UPDATE users
    SET status = 'blocked', updated_at = now()
    WHERE users.id = $1
    RETURNING users.id
), deleted_sessions AS (
    DELETE FROM sessions
    WHERE sessions.user_id IN (SELECT blocked.id FROM blocked)
    RETURNING sessions.id
)
SELECT count(*) FROM blocked
`

func (q *Queries) BlockUserAndDeleteSessions(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, blockUserAndDeleteSessions, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, role, status, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, role, status, created_at, updated_at
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserStatus = `-- name: SetUserStatus :execrows
UPDATE users
SET status = $1, updated_at = now()
WHERE id = $2
`

type SetUserStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertUserFromLDAP = `-- name: UpsertUserFromLDAP :one
INSERT INTO users (username, email, role)
VALUES ($1, $2, $3)
ON CONFLICT (username) DO UPDATE SET
    email = EXCLUDED.email,
    role = EXCLUDED.role,
    updated_at = now()
RETURNING id, username, email, role, status, created_at, updated_at
`

type UpsertUserFromLDAPParams struct {
	Username string      `json:"username"`
	Email    pgtype.Text `json:"email"`
	Role     string      `json:"role"`
}

func (q *Queries) UpsertUserFromLDAP(ctx context.Context, arg UpsertUserFromLDAPParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserFromLDAP, arg.Username, arg.Email, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
